/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.dumpandgo.ejb.local;

/**
 * Local home interface for DumpAndGoPlugin.
 * @xdoclet-generated at 18-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface DumpAndGoPluginLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/DumpAndGoPluginLocal";
   public static final String JNDI_NAME="amalto/local/transformer/plugin/dumpandgo";

   public com.amalto.core.plugin.base.dumpandgo.ejb.local.DumpAndGoPluginLocal create()
      throws javax.ejb.CreateException;

}
