/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.ejb.local;

import com.amalto.core.server.XmlServer;

/**
 * Local interface for XmlServerSLWrapper.
 * 
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface XmlServerSLWrapperLocal extends javax.ejb.EJBLocalObject, XmlServer {
}
