/*
 * Generated by XDoclet - Do not edit!
 */
package org.talend.mdm.server.api;

public interface Role {
    /**
     * Creates or updates a Role
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public com.amalto.core.objects.role.ejb.RolePOJOPK putRole(com.amalto.core.objects.role.ejb.RolePOJO role)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

    /**
     * Get Role
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public com.amalto.core.objects.role.ejb.RolePOJO getRole(com.amalto.core.objects.role.ejb.RolePOJOPK pk)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

    /**
     * Get a Role - no exception is thrown: returns null if not found
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public com.amalto.core.objects.role.ejb.RolePOJO existsRole(com.amalto.core.objects.role.ejb.RolePOJOPK pk)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

    /**
     * Remove an item
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public com.amalto.core.objects.role.ejb.RolePOJOPK removeRole(com.amalto.core.objects.role.ejb.RolePOJOPK pk)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

    /**
     * Retrieve all Role PKS
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public java.util.Collection getRolePKs(String regex)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

}
