/*
 * Generated by XDoclet - Do not edit!
 */
package org.talend.mdm.server.api;

public interface RoutingRule  {
   /**
    * Creates or updates a menu
    */
   public com.amalto.core.objects.routing.v2.ejb.RoutingRulePOJOPK putRoutingRule(com.amalto.core.objects.routing.v2.ejb.RoutingRulePOJO routingRule)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Get menu
    */
   public com.amalto.core.objects.routing.v2.ejb.RoutingRulePOJO getRoutingRule(com.amalto.core.objects.routing.v2.ejb.RoutingRulePOJOPK pk)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Get a RoutingRule - no exception is thrown: returns null if not found
    */
   public com.amalto.core.objects.routing.v2.ejb.RoutingRulePOJO existsRoutingRule(com.amalto.core.objects.routing.v2.ejb.RoutingRulePOJOPK pk)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Remove a RoutingRule
    */
   public com.amalto.core.objects.routing.v2.ejb.RoutingRulePOJOPK removeRoutingRule(com.amalto.core.objects.routing.v2.ejb.RoutingRulePOJOPK pk)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Retrieve all RoutingRule PKs
    */
   public java.util.Collection getRoutingRulePKs(String regex)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

}
