/*
 * Generated by XDoclet - Do not edit!
 */
package org.talend.mdm.server.api;

public interface View {
    /**
     * Creates or updates a View
     */
    public com.amalto.core.objects.view.ejb.ViewPOJOPK putView(com.amalto.core.objects.view.ejb.ViewPOJO view)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

    /**
     * Get item
     */
    public com.amalto.core.objects.view.ejb.ViewPOJO getView(com.amalto.core.objects.view.ejb.ViewPOJOPK pk)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

    /**
     * Get a View - no exception is thrown: returns null if not found
     */
    public com.amalto.core.objects.view.ejb.ViewPOJO existsView(com.amalto.core.objects.view.ejb.ViewPOJOPK pk)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

    /**
     * Remove an item
     */
    public com.amalto.core.objects.view.ejb.ViewPOJOPK removeView(com.amalto.core.objects.view.ejb.ViewPOJOPK pk)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

    /**
     * Retrieve all View PKS
     */
    public java.util.Collection getViewPKs(String regex)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

    /**
     * Retrieve all Views
     */
    public java.util.ArrayList getAllViews(String regex)
            throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

}
