// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSHashMap {
    protected com.amalto.core.webservice.WSStartProcessInstanceVariableEntry[] entry;
    
    public WSHashMap() {
    }
    
    public WSHashMap(com.amalto.core.webservice.WSStartProcessInstanceVariableEntry[] entry) {
        this.entry = entry;
    }
    
    public com.amalto.core.webservice.WSStartProcessInstanceVariableEntry[] getEntry() {
        return entry;
    }
    
    public void setEntry(com.amalto.core.webservice.WSStartProcessInstanceVariableEntry[] entry) {
        this.entry = entry;
    }
}
