// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSIsItemModifiedByOther {
    protected com.amalto.core.webservice.WSItem wsItem;
    
    public WSIsItemModifiedByOther() {
    }
    
    public WSIsItemModifiedByOther(com.amalto.core.webservice.WSItem wsItem) {
        this.wsItem = wsItem;
    }
    
    public com.amalto.core.webservice.WSItem getWsItem() {
        return wsItem;
    }
    
    public void setWsItem(com.amalto.core.webservice.WSItem wsItem) {
        this.wsItem = wsItem;
    }
}
