// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


import java.util.Map;
import java.util.HashMap;

public class WSTaskPriority {
    private java.lang.String value;
    private static Map valueMap = new HashMap();
    public static final String _NORMALString = "NORMAL";
    public static final String _HIGHString = "HIGH";
    public static final String _URGENTString = "URGENT";
    
    public static final java.lang.String _NORMAL = new java.lang.String(_NORMALString);
    public static final java.lang.String _HIGH = new java.lang.String(_HIGHString);
    public static final java.lang.String _URGENT = new java.lang.String(_URGENTString);
    
    public static final WSTaskPriority NORMAL = new WSTaskPriority(_NORMAL);
    public static final WSTaskPriority HIGH = new WSTaskPriority(_HIGH);
    public static final WSTaskPriority URGENT = new WSTaskPriority(_URGENT);
    
    protected WSTaskPriority(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static WSTaskPriority fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (NORMAL.value.equals(value)) {
            return NORMAL;
        } else if (HIGH.value.equals(value)) {
            return HIGH;
        } else if (URGENT.value.equals(value)) {
            return URGENT;
        }
        throw new IllegalArgumentException();
    }
    
    public static WSTaskPriority fromString(String value)
        throws java.lang.IllegalStateException {
        WSTaskPriority ret = (WSTaskPriority)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_NORMALString)) {
            return NORMAL;
        } else if (value.equals(_HIGHString)) {
            return HIGH;
        } else if (value.equals(_URGENTString)) {
            return URGENT;
        }
        throw new IllegalArgumentException();
    }
    
    public String toString() {
        return value.toString();
    }
    
    private Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(Object obj) {
        if (!(obj instanceof WSTaskPriority)) {
            return false;
        }
        return ((WSTaskPriority)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
