/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.routing.v2.ejb.local;

import com.amalto.core.server.RoutingEngine;

/**
 * Local interface for RoutingEngineV2Ctrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface RoutingEngineV2CtrlLocal extends javax.ejb.EJBLocalObject, RoutingEngine {

}
