/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.datamodel.ejb.local;

import com.amalto.core.server.DataModel;

/**
 * Local interface for DataModelCtrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface DataModelCtrlLocal extends javax.ejb.EJBLocalObject, DataModel {
}
