/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.customform.ejb.local;

/**
 * Local home interface for CustomFormCtrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CustomFormCtrlLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CustomFormCtrlLocal";
   public static final String JNDI_NAME="amalto/local/core/customformctrl";

   public com.amalto.core.objects.customform.ejb.local.CustomFormCtrlLocal create()
      throws javax.ejb.CreateException;

}
