/*
 * Copyright (C) 2006-2016 Talend Inc. - www.talend.com
 * 
 * This source code is available under agreement available at
 * %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
 * 
 * You should have received a copy of the agreement along with this program; if not, write to Talend SA 9 rue Pages
 * 92150 Suresnes, France
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.server.api;

import com.amalto.core.objects.role.RolePOJO;
import com.amalto.core.objects.role.RolePOJOPK;

public interface Role {

    /**
     * Creates or updates a Role
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public RolePOJOPK putRole(RolePOJO role) throws com.amalto.core.util.XtentisException;

    /**
     * Get Role
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public RolePOJO getRole(RolePOJOPK pk) throws com.amalto.core.util.XtentisException;

    /**
     * Get a Role - no exception is thrown: returns null if not found
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public RolePOJO existsRole(RolePOJOPK pk) throws com.amalto.core.util.XtentisException;

    /**
     * Remove an item
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public RolePOJOPK removeRole(RolePOJOPK pk) throws com.amalto.core.util.XtentisException;

    /**
     * Retrieve all Role PKS
     *
     * @throws com.amalto.core.util.XtentisException
     */
    public java.util.Collection getRolePKs(String regex) throws com.amalto.core.util.XtentisException;

}
