/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.server.api;

import com.amalto.core.objects.routing.RoutingRulePOJO;
import com.amalto.core.objects.routing.RoutingRulePOJOPK;

public interface RoutingRule  {
   /**
    * Creates or updates a menu
    */
   public RoutingRulePOJOPK putRoutingRule(RoutingRulePOJO routingRule)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Get menu
    */
   public RoutingRulePOJO getRoutingRule(RoutingRulePOJOPK pk)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Get a RoutingRule - no exception is thrown: returns null if not found
    */
   public RoutingRulePOJO existsRoutingRule(RoutingRulePOJOPK pk)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Remove a RoutingRule
    */
   public RoutingRulePOJOPK removeRoutingRule(RoutingRulePOJOPK pk)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Retrieve all RoutingRule PKs
    */
   public java.util.Collection getRoutingRulePKs(String regex)
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

}
