/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.server.api;

import com.amalto.core.objects.universe.RevisionPOJOPK;
import com.amalto.core.objects.universe.UniversePOJO;
import com.amalto.core.objects.universe.UniversePOJOPK;
import com.amalto.core.util.XtentisException;

public interface Universe {
   /**
    * Creates or updates a Universe
    * @throws com.amalto.core.util.XtentisException
    */
   public UniversePOJOPK putUniverse(UniversePOJO universe) throws XtentisException;

   /**
    * Creates or updates a Universe
    * @throws com.amalto.core.util.XtentisException
    */
   public com.amalto.core.webservice.WSUniversePKArray getUniverseByRevision(String name, String revision, String type) throws XtentisException;

   /**
    * Get Universe
    * @throws com.amalto.core.util.XtentisException
    */
   public UniversePOJO getUniverse(UniversePOJOPK pk) throws XtentisException;

   /**
    * Get a Universe - no exception is thrown: returns null if not found
    * @throws com.amalto.core.util.XtentisException
    */
   public UniversePOJO existsUniverse(UniversePOJOPK pk) throws XtentisException;

   /**
    * Remove an item
    * @throws com.amalto.core.util.XtentisException
    */
   public UniversePOJOPK removeUniverse(UniversePOJOPK pk) throws XtentisException;

   /**
    * getAllCreatedRevisions
    */
   public java.util.Collection getAllCreatedRevisions(UniversePOJOPK pk) ;

   /**
    * getAllQuotedRevisions
    */
   public java.util.Collection getAllQuotedRevisions(UniversePOJOPK pk) ;

   /**
    * getUniverseCreator
    */
   public UniversePOJOPK getUniverseCreator(RevisionPOJOPK pk) ;

   /**
    * getUniverseQuoter
    */
   public java.util.Collection getUniverseQuoter(RevisionPOJOPK pk) ;

   /**
    * Retrieve all Universe PKS
    * @throws com.amalto.core.util.XtentisException
    */
   public java.util.Collection getUniversePKs(String regex) throws XtentisException;

}
