/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.server.api;

import com.amalto.core.util.XtentisException;

public interface Universe {
   /**
    * Creates or updates a Universe
    * @throws com.amalto.core.util.XtentisException
    */
   public com.amalto.core.objects.universe.ejb.UniversePOJOPK putUniverse(com.amalto.core.objects.universe.ejb.UniversePOJO universe) throws XtentisException;

   /**
    * Creates or updates a Universe
    * @throws com.amalto.core.util.XtentisException
    */
   public com.amalto.core.webservice.WSUniversePKArray getUniverseByRevision(String name, String revision, String type) throws XtentisException;

   /**
    * Get Universe
    * @throws com.amalto.core.util.XtentisException
    */
   public com.amalto.core.objects.universe.ejb.UniversePOJO getUniverse(com.amalto.core.objects.universe.ejb.UniversePOJOPK pk) throws XtentisException;

   /**
    * Get a Universe - no exception is thrown: returns null if not found
    * @throws com.amalto.core.util.XtentisException
    */
   public com.amalto.core.objects.universe.ejb.UniversePOJO existsUniverse(com.amalto.core.objects.universe.ejb.UniversePOJOPK pk) throws XtentisException;

   /**
    * Remove an item
    * @throws com.amalto.core.util.XtentisException
    */
   public com.amalto.core.objects.universe.ejb.UniversePOJOPK removeUniverse(com.amalto.core.objects.universe.ejb.UniversePOJOPK pk) throws XtentisException;

   /**
    * getAllCreatedRevisions
    */
   public java.util.Collection getAllCreatedRevisions(com.amalto.core.objects.universe.ejb.UniversePOJOPK pk) ;

   /**
    * getAllQuotedRevisions
    */
   public java.util.Collection getAllQuotedRevisions(com.amalto.core.objects.universe.ejb.UniversePOJOPK pk) ;

   /**
    * getUniverseCreator
    */
   public com.amalto.core.objects.universe.ejb.UniversePOJOPK getUniverseCreator(com.amalto.core.objects.universe.ejb.RevisionPOJOPK pk) ;

   /**
    * getUniverseQuoter
    */
   public java.util.Collection getUniverseQuoter(com.amalto.core.objects.universe.ejb.RevisionPOJOPK pk) ;

   /**
    * Retrieve all Universe PKS
    * @throws com.amalto.core.util.XtentisException
    */
   public java.util.Collection getUniversePKs(String regex) throws XtentisException;

}
