create table AccountManager (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyrole));
create table Address (x_idaddress varchar(255) not null, x_addresstype varchar(255), x_addressquality varchar(255), x_namefk_x_idname varchar(255), x_partycommchan_785316328 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idaddress));
create table AllowedCommChannelTypes (x_idallowedcommchanneltypes varchar(255) not null, x_commchannelty_1999936045 varchar(255), x_partyfk_x_idparty varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idallowedcommchanneltypes));
create table Bank (x_idparty varchar(255) not null, x_partytype varchar(255), x_sixtid integer, x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_firma varchar(255), x_legalform varchar(255), x_hregno varchar(255), x_foundedplace varchar(255), x_hregcode varchar(255), x_hregplace varchar(255), x_costcenter varchar(255), x_industry varchar(255), x_fir varchar(255), x_parentorganis1889123935 varchar(255), x_insolvent integer, x_genericlabel varchar(255), x_remark varchar(255), x_foundeddate timestamp, x_countryid_x_idcountry varchar(255), x_blz varchar(255), x_bic varchar(255), primary key (x_idparty));
create table BankAccount (x_idpartyaccount varchar(255) not null, x_partyfk_x_idparty varchar(255), x_partyrolefk_x_idpartyrole varchar(255), x_currencyfk_x_idcurrency varchar(255), x_partyaccounttype varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyaccount));
create table Booker (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyrole));
create table CommChannelType (x_idcommchanneltype varchar(255) not null, x_name varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idcommchanneltype));
create table CommChannelUsage (x_idcommchannelusage varchar(255) not null, x_usedbypartyro_1121959463 varchar(255), x_partycommchan_785316328 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idcommchannelusage));
create table CommChannelUsageChars (x_idcommchannelusagechars varchar(255) not null, x_commchannelus_1254398681 varchar(255), x_commchannelusagetype varchar(255), x_commchannelpreferred varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idcommchannelusagechars));
create table Contact (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_contactleadsource varchar(255), x_contacttype varchar(255), x_contacttopic varchar(255), primary key (x_idpartyrole));
create table Country (x_idcountry varchar(255) not null, x_countryname varchar(255), x_countrycode varchar(255), x_countrydialprefix varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idcountry));
create table CountryCurrencyChars (x_idcountrycurrencychars varchar(255) not null, x_countryfk_x_idcountry varchar(255), x_currencyfk_x_idcurrency varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idcountrycurrencychars));
create table CreditCard (x_idpartyidentification varchar(255) not null, x_partyidentificationtype varchar(255), x_cctype varchar(255), x_ccnumber varchar(255), x_holdersalutation varchar(255), x_holderacademictitle varchar(255), x_holderfirstname varchar(255), x_holderlastname varchar(255), x_issueddate timestamp, x_expirydate timestamp, x_creditcardacc_2032180649 varchar(255), x_ccstatus varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyidentification));
create table CreditCardAccount (x_idpartyaccount varchar(255) not null, x_partyfk_x_idparty varchar(255), x_partyrolefk_x_idpartyrole varchar(255), x_currencyfk_x_idcurrency varchar(255), x_partyaccounttype varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyaccount));
create table Currency (x_idcurrency varchar(255) not null, x_currencyname varchar(255), x_currencysymbol varchar(255), x_currencyshort varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idcurrency));
create table Debitor (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_creditlimit double, x_creditamount double, x_oldit_bonitatsprioritat varchar(255), x_debitornumber varchar(255), x_creditcurrenc1895526388 varchar(255), primary key (x_idpartyrole));
create table DebitorAccount (x_idpartyaccount varchar(255) not null, x_partyfk_x_idparty varchar(255), x_partyrolefk_x_idpartyrole varchar(255), x_currencyfk_x_idcurrency varchar(255), x_partyaccounttype varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyaccount));
create table Driver (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyrole));
create table EMailAddress (x_idaddress varchar(255) not null, x_addresstype varchar(255), x_addressquality varchar(255), x_namefk_x_idname varchar(255), x_partycommchan_785316328 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_emailaddress varchar(255), primary key (x_idaddress));
create table Employment (x_idemployment varchar(255) not null, x_employspersonfk_x_idparty varchar(255), x_employedbyorg1719897384 varchar(255), x_description varchar(255), x_enterprisefunction varchar(255), x_internalname varchar(255), x_personnelnumber varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idemployment));
create table FrameContractPartner (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyrole));
create table IdentityCard (x_idpartyidentification varchar(255) not null, x_partyidentificationtype varchar(255), x_idcardtype varchar(255), x_idcardnumber varchar(255), x_issuedplace varchar(255), x_issueddate timestamp, x_expirydate timestamp, x_lastname varchar(255), x_firstname varchar(255), x_idcardissuedc_151126323 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyidentification));
create table InterPersonRelationship (x_idinterpersonrelationship varchar(255) not null, x_frompersonfk_x_idparty varchar(255), x_topersonfk_x_idparty varchar(255), x_interpersonreltype varchar(255), x_interpersrelattr varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idinterpersonrelationship));
create table InvoicerRecipient (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyrole));
create table LoyaltyAccount (x_idpartyaccount varchar(255) not null, x_partyfk_x_idparty varchar(255), x_partyrolefk_x_idpartyrole varchar(255), x_currencyfk_x_idcurrency varchar(255), x_partyaccounttype varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyaccount));
create table LoyaltyCard (x_idpartyidentification varchar(255) not null, x_partyidentificationtype varchar(255), x_loyaltycardnumber varchar(255), x_firstname varchar(255), x_lastname varchar(255), x_issueddate timestamp, x_expirydate timestamp, x_loyaltycardtype varchar(255), x_loyaltycardstatus varchar(255), x_loyaltyaccoun1988503311 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyidentification));
create table OccupationGroup (x_idoccupationgroup varchar(255) not null, x_ogname varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idoccupationgroup));
create table OccupationGrouping (x_idoccupationgrouping varchar(255) not null, x_describepersonfk_x_idparty varchar(255), x_worksinoccupa_1747157821 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idoccupationgrouping));
create table OrgaMesh (x_idorgamesh varchar(255) not null, x_fromorgafk_x_idparty varchar(255), x_toorgafk_x_idparty varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idorgamesh));
create table OrgaMeshChars (x_idorgameshchars varchar(255) not null, x_attribute varchar(255), x_valuestring varchar(255), x_valuenum double, x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idorgameshchars));
create table Organisation (x_idparty varchar(255) not null, x_partytype varchar(255), x_sixtid integer, x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_firma varchar(255), x_legalform varchar(255), x_hregno varchar(255), x_foundedplace varchar(255), x_hregcode varchar(255), x_hregplace varchar(255), x_costcenter varchar(255), x_industry varchar(255), x_fir varchar(255), x_parentorganis1889123935 varchar(255), x_insolvent integer, x_genericlabel varchar(255), x_remark varchar(255), x_foundeddate timestamp, primary key (x_idparty));
create table Party (x_idparty varchar(255) not null, x_partytype varchar(255), x_sixtid integer, x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idparty));
create table PartyAccount (x_idpartyaccount varchar(255) not null, x_partyfk_x_idparty varchar(255), x_partyrolefk_x_idpartyrole varchar(255), x_currencyfk_x_idcurrency varchar(255), x_partyaccounttype varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyaccount));
create table PartyAccountStats (x_idpartyaccountstats varchar(255) not null, x_type varchar(255), x_value double, x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyaccountstats));
create table PartyCommChannel (x_idpartycommchannel varchar(255) not null, x_partyfk_x_idparty varchar(255), x_commchannelty2030335850 varchar(255), x_commchannelblocked varchar(255), x_addressfk_x_idaddress varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartycommchannel));
create table PartyRole (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyrole));
create table Person (x_idparty varchar(255) not null, x_partytype varchar(255), x_sixtid integer, x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_namefk_x_idname varchar(255), x_birthday timestamp, x_birthplace varchar(255), x_birthcountry varchar(255), x_gender varchar(255), x_birthname varchar(255), x_nationality varchar(255), x_maritalstatus varchar(255), x_children varchar(255), x_skills varchar(255), primary key (x_idparty));
create table PhoneAddress (x_idaddress varchar(255) not null, x_addresstype varchar(255), x_addressquality varchar(255), x_namefk_x_idname varchar(255), x_partycommchan_785316328 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_areaprefix varchar(255), x_localprefix varchar(255), x_localnumber varchar(255), x_extension varchar(255), x_part1 varchar(255), x_part2 varchar(255), x_postfix1 varchar(255), x_postfix2 varchar(255), x_countryfk_x_idcountry varchar(255), primary key (x_idaddress));
create table PostalAddress (x_idaddress varchar(255) not null, x_addresstype varchar(255), x_addressquality varchar(255), x_namefk_x_idname varchar(255), x_partycommchan_785316328 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_state varchar(255), x_province varchar(255), x_city varchar(255), x_zip varchar(255), x_street varchar(255), x_number varchar(255), x_postbox varchar(255), x_adr_1 varchar(255), x_adr_2 varchar(255), x_adr_3 varchar(255), x_adr_4 varchar(255), x_countryfk_x_idcountry varchar(255), primary key (x_idaddress));
create table RelMgmt (x_idrelmgmt varchar(255) not null, x_relmanagedbyp1924112687 varchar(255), x_islookedafter_720055100 varchar(255), x_relmgmttype varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idrelmgmt));
create table RentalCustomer (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_rentalcustomertype varchar(255), x_hasinsurance integer, x_guarantee varchar(255), x_deposit varchar(255), x_channel varchar(255), x_guaranteevalid varchar(255), primary key (x_idpartyrole));
create table Risk (x_idrisk varchar(255) not null, x_riskprofilefk821433260 varchar(255), x_risktype varchar(255), x_riskname varchar(255), x_description varchar(255), x_riskvalue double, x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idrisk));
create table RiskProfil (x_idriskprofil varchar(255) not null, x_partyrolefk_x_idpartyrole varchar(255), x_riskprofiletype varchar(255), x_lastupdated timestamp, x_riskvalue integer, x_min integer, x_max integer, x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idriskprofil));
create table RoleInSegment (x_idroleinsegment varchar(255) not null, x_partyrolefk_x_idpartyrole varchar(255), x_segmentfk_x_idsegment varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idroleinsegment));
create table SalesAccount (x_idpartyaccount varchar(255) not null, x_partyfk_x_idparty varchar(255), x_partyrolefk_x_idpartyrole varchar(255), x_currencyfk_x_idcurrency varchar(255), x_partyaccounttype varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyaccount));
create table Segment (x_idsegment varchar(255) not null, x_name varchar(255), x_description varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idsegment));
create table SelfInfo (x_idselfinfo varchar(255) not null, x_debitorfk_x_idpartyrole varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idselfinfo));
create table ServiceProvider (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_abbreviation varchar(255), primary key (x_idpartyrole));
create table ServiceRecipient (x_idpartyrole varchar(255) not null, x_partyroletype varchar(255), x_belongstoparty_x_idparty varchar(255), x_comments varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyrole));
create table TALEND_TASK_EXECUTION (x_id varchar(255) not null, x_type varchar(255), x_start_time bigint, x_end_match_time bigint, x_end_time bigint, x_error_count decimal(19,2), x_record_count decimal(19,2), x_completed boolean, x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_id));
create table UserAccount (x_idpartyaccount varchar(255) not null, x_partyfk_x_idparty varchar(255), x_partyrolefk_x_idpartyrole varchar(255), x_currencyfk_x_idcurrency varchar(255), x_partyaccounttype varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyaccount));
create table WebsiteAddress (x_idaddress varchar(255) not null, x_addresstype varchar(255), x_addressquality varchar(255), x_namefk_x_idname varchar(255), x_partycommchan_785316328 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, x_url varchar(255), primary key (x_idaddress));
create table XRef (x_idcxref varchar(255) not null, x_entity varchar(255), x_mdmkey varchar(255), x_externalrefer_1655348832 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idcxref));
create table X_ANONYMOUS0 (x_talend_id varchar(255) not null, primary key (x_talend_id));
create table X_ANONYMOUS0_x__954682972 (x_talend_id varchar(255) not null, x_externalrefer_373841693 varchar(255), pos integer not null, primary key (x_talend_id, pos));
create table X_Login (x_idpartyidentification varchar(255) not null, x_partyidentificationtype varchar(255), x_username varchar(255), x_password varchar(255), x_passwordquestion varchar(255), x_passwordquestionresponce varchar(255), x_md5 varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idpartyidentification));
create table X_Name (x_idname varchar(255) not null, x_academictitle varchar(255), x_firstname varchar(255), x_middlename varchar(255), x_lastname varchar(255), x_nobilitytitle varchar(255), x_furthertitle varchar(255), x_salutation varchar(255), x_personfk_x_idparty varchar(255), x_talend_timestamp bigint, x_talend_task_id varchar(36), x_talend_staging_status integer, x_talend_staging_source varchar(36), x_talend_staging_blockkey varchar(36), x_talend_staging_error longvarchar, x_talend_staging_values longvarchar, primary key (x_idname));
create table X_XRef_ExternalRefType (x_talend_id varchar(255) not null, x_systemname varchar(255) not null, x_systemkey varchar(255) not null, x_systemmain boolean, x_firstloadtime timestamp, x_lastloadtime timestamp, x_deletedtime timestamp, primary key (x_talend_id));
create index AccountManagerP985554384 on AccountManager (x_talend_staging_status);
create index AccountManagerP617063773 on AccountManager (x_talend_staging_blockkey);
create index AccountManagerP_162328477 on AccountManager (x_talend_task_id);
create index Address_x_talen_1142433852 on Address (x_talend_staging_blockkey);
create index Address_x_talen2083514564 on Address (x_talend_staging_status);
create index Address_x_talen_655897203 on Address (x_talend_task_id);
create index AllowedCommChan_1540634390 on AllowedCommChannelTypes (x_talend_staging_status);
create index AllowedCommChan_731101590 on AllowedCommChannelTypes (x_talend_staging_blockkey);
create index AllowedCommChan_1585763289 on AllowedCommChannelTypes (x_talend_task_id);
create index BankParty_x_talend_1127213001 on Bank (x_talend_staging_status);
create index BankParty_x_tal_325535237 on Bank (x_talend_staging_blockkey);
create index BankParty_x_tal_1734755900 on Bank (x_talend_task_id);
create index BankAccountPart_1137517100 on BankAccount (x_talend_staging_blockkey);
create index BankAccountPart_1478095109 on BankAccount (x_talend_staging_status);
create index BankAccountPart_370840971 on BankAccount (x_talend_task_id);
create index BookerPartyRole_1411032636 on Booker (x_talend_staging_status);
create index BookerPartyRole_1779523247 on Booker (x_talend_staging_blockkey);
create index BookerPartyRole_1442082065 on Booker (x_talend_task_id);
create index CommChannelType1729158 on CommChannelType (x_talend_staging_blockkey);
create index CommChannelType900348934 on CommChannelType (x_talend_staging_status);
create index CommChannelType_1394360181 on CommChannelType (x_talend_task_id);
create index CommChannelUsag1971404203 on CommChannelUsage (x_talend_staging_status);
create index CommChannelUsag427892358 on CommChannelUsage (x_talend_task_id);
create index CommChannelUsag_1506308373 on CommChannelUsage (x_talend_staging_blockkey);
create index CommChannelUsag2088558846 on CommChannelUsageChars (x_talend_staging_blockkey);
create index CommChannelUsag245013267 on CommChannelUsageChars (x_talend_task_id);
create index CommChannelUsag_1962280834 on CommChannelUsageChars (x_talend_staging_status);
create index ContactPartyRol2129260585 on Contact (x_talend_staging_status);
create index ContactPartyRol1760769974 on Contact (x_talend_staging_blockkey);
create index ContactPartyRol932825386 on Contact (x_talend_task_id);
create index Country_x_talen2083514564 on Country (x_talend_staging_status);
create index Country_x_talen_655897203 on Country (x_talend_task_id);
create index Country_x_talen_1142433852 on Country (x_talend_staging_blockkey);
create index CountryCurrency_1374110973 on CountryCurrencyChars (x_talend_staging_status);
create index CountryCurrency_1038781394 on CountryCurrencyChars (x_talend_task_id);
create index CountryCurrency384112195 on CountryCurrencyChars (x_talend_staging_blockkey);
create index CreditCard_x_ta1905904345 on CreditCard (x_talend_staging_blockkey);
create index CreditCard_x_ta_1904370407 on CreditCard (x_talend_staging_status);
create index CreditCard_x_ta_2044387624 on CreditCard (x_talend_task_id);
create index CreditCardAccou_35668837 on CreditCardAccount (x_talend_staging_blockkey);
create index CreditCardAccou_749814956 on CreditCardAccount (x_talend_staging_status);
create index CreditCardAccou731007292 on CreditCardAccount (x_talend_task_id);
create index Currency_x_tale_2002194894 on Currency (x_talend_staging_blockkey);
create index Currency_x_tale_980081825 on Currency (x_talend_task_id);
create index Currency_x_tale1568654002 on Currency (x_talend_staging_status);
create index DebitorPartyRol2129260585 on Debitor (x_talend_staging_status);
create index DebitorPartyRol1760769974 on Debitor (x_talend_staging_blockkey);
create index DebitorPartyRol932825386 on Debitor (x_talend_task_id);
create index DebitorAccountP930664273 on DebitorAccount (x_talend_staging_blockkey);
create index DebitorAccountP1636661726 on DebitorAccount (x_talend_staging_status);
create index DebitorAccountP1697340402 on DebitorAccount (x_talend_task_id);
create index DriverPartyRole_1411032636 on Driver (x_talend_staging_status);
create index DriverPartyRole_1779523247 on Driver (x_talend_staging_blockkey);
create index DriverPartyRole_1442082065 on Driver (x_talend_task_id);
create index EMailAddressAdd1528379849 on EMailAddress (x_talend_staging_blockkey);
create index EMailAddressAdd_626580503 on EMailAddress (x_talend_staging_status);
create index EMailAddressAdd2095327051 on EMailAddress (x_talend_task_id);
create index Employment_x_ta_2044387624 on Employment (x_talend_task_id);
create index Employment_x_ta1905904345 on Employment (x_talend_staging_blockkey);
create index Employment_x_ta_1904370407 on Employment (x_talend_staging_status);
create index FrameContractPa2021797927 on FrameContractPartner (x_talend_staging_status);
create index FrameContractPa1653307316 on FrameContractPartner (x_talend_staging_blockkey);
create index FrameContractPa1896450284 on FrameContractPartner (x_talend_task_id);
create index IdentityCard_x_1761681484 on IdentityCard (x_talend_staging_blockkey);
create index IdentityCard_x_1762216965 on IdentityCard (x_talend_task_id);
create index IdentityCard_x_982627148 on IdentityCard (x_talend_staging_status);
create index InterPersonRela_1327651370 on InterPersonRelationship (x_talend_staging_blockkey);
create index InterPersonRela_1912204458 on InterPersonRelationship (x_talend_staging_status);
create index InterPersonRela_925334725 on InterPersonRelationship (x_talend_task_id);
create index InvoicerRecipie19221274 on InvoicerRecipient (x_talend_staging_status);
create index InvoicerRecipie_349269337 on InvoicerRecipient (x_talend_staging_blockkey);
create index InvoicerRecipie_53883815 on InvoicerRecipient (x_talend_task_id);
create index LoyaltyAccountP930664273 on LoyaltyAccount (x_talend_staging_blockkey);
create index LoyaltyAccountP1636661726 on LoyaltyAccount (x_talend_staging_status);
create index LoyaltyAccountP1697340402 on LoyaltyAccount (x_talend_task_id);
create index LoyaltyCard_x_t1941186809 on LoyaltyCard (x_talend_task_id);
create index LoyaltyCard_x_t_1328704040 on LoyaltyCard (x_talend_staging_blockkey);
create index LoyaltyCard_x_t1104550872 on LoyaltyCard (x_talend_staging_status);
create index OccupationGroup900348934 on OccupationGroup (x_talend_staging_status);
create index OccupationGroup_1394360181 on OccupationGroup (x_talend_task_id);
create index OccupationGroup1729158 on OccupationGroup (x_talend_staging_blockkey);
create index OccupationGroup343143016 on OccupationGrouping (x_talend_staging_blockkey);
create index OccupationGroup_1603769751 on OccupationGrouping (x_talend_task_id);
create index OccupationGroup_1047896984 on OccupationGrouping (x_talend_staging_status);
create index OrgaMesh_x_tale_980081825 on OrgaMesh (x_talend_task_id);
create index OrgaMesh_x_tale_2002194894 on OrgaMesh (x_talend_staging_blockkey);
create index OrgaMesh_x_tale1568654002 on OrgaMesh (x_talend_staging_status);
create index OrgaMeshChars_x365717220 on OrgaMeshChars (x_talend_task_id);
create index OrgaMeshChars_x_1458253747 on OrgaMeshChars (x_talend_staging_blockkey);
create index OrgaMeshChars_x_1742508147 on OrgaMeshChars (x_talend_staging_status);
create index OrganisationPar596165380 on Organisation (x_talend_staging_status);
create index OrganisationPar2132962589 on Organisation (x_talend_staging_blockkey);
create index OrganisationPar_1350357914 on Organisation (x_talend_task_id);
create index Party_x_talend_1127213001 on Party (x_talend_staging_status);
create index Party_x_talend__1025234551 on Party (x_talend_staging_blockkey);
create index Party_x_talend_task_id_index on Party (x_talend_task_id);
create index PartyAccount_x_1761681484 on PartyAccount (x_talend_staging_blockkey);
create index PartyAccount_x_982627148 on PartyAccount (x_talend_staging_status);
create index PartyAccount_x_1762216965 on PartyAccount (x_talend_task_id);
create index PartyAccountSta_948317396 on PartyAccountStats (x_talend_task_id);
create index PartyAccountSta1343824453 on PartyAccountStats (x_talend_staging_status);
create index PartyAccountSta979940613 on PartyAccountStats (x_talend_staging_blockkey);
create index PartyCommChanne_41154913 on PartyCommChannel (x_talend_task_id);
create index PartyCommChanne387822322 on PartyCommChannel (x_talend_staging_blockkey);
create index PartyCommChanne132036466 on PartyCommChannel (x_talend_staging_status);
create index PartyRole_x_tal_904060755 on PartyRole (x_talend_staging_status);
create index PartyRole_x_tal1130805613 on PartyRole (x_talend_staging_blockkey);
create index PartyRole_x_tal_1734755900 on PartyRole (x_talend_task_id);
create index PersonParty_x_t1587300177 on Person (x_talend_staging_status);
create index PersonParty_x_t_1501597072 on Person (x_talend_staging_blockkey);
create index PersonParty_x_t1941186809 on Person (x_talend_task_id);
create index PhoneAddressAdd1528379849 on PhoneAddress (x_talend_staging_blockkey);
create index PhoneAddressAdd_626580503 on PhoneAddress (x_talend_staging_status);
create index PhoneAddressAdd2095327051 on PhoneAddress (x_talend_task_id);
create index PostalAddressAd_877328155 on PostalAddress (x_talend_staging_blockkey);
create index PostalAddressAd_704183987 on PostalAddress (x_talend_staging_status);
create index PostalAddressAd2017723567 on PostalAddress (x_talend_task_id);
create index RelMgmt_x_talen2083514564 on RelMgmt (x_talend_staging_status);
create index RelMgmt_x_talen_1142433852 on RelMgmt (x_talend_staging_blockkey);
create index RelMgmt_x_talen_655897203 on RelMgmt (x_talend_task_id);
create index RentalCustomerP985554384 on RentalCustomer (x_talend_staging_status);
create index RentalCustomerP617063773 on RentalCustomer (x_talend_staging_blockkey);
create index RentalCustomerP_162328477 on RentalCustomer (x_talend_task_id);
create index Risk_x_talend_s897358620 on Risk (x_talend_staging_status);
create index Risk_x_talend_s1423004700 on Risk (x_talend_staging_blockkey);
create index Risk_x_talend_task_id_index on Risk (x_talend_task_id);
create index RiskProfil_x_ta_1904370407 on RiskProfil (x_talend_staging_status);
create index RiskProfil_x_ta_2044387624 on RiskProfil (x_talend_task_id);
create index RiskProfil_x_ta1905904345 on RiskProfil (x_talend_staging_blockkey);
create index RoleInSegment_x365717220 on RoleInSegment (x_talend_task_id);
create index RoleInSegment_x_1458253747 on RoleInSegment (x_talend_staging_blockkey);
create index RoleInSegment_x_1742508147 on RoleInSegment (x_talend_staging_status);
create index SalesAccountPar_1328845344 on SalesAccount (x_talend_staging_blockkey);
create index SalesAccountPar1563774319 on SalesAccount (x_talend_staging_status);
create index SalesAccountPar_562169215 on SalesAccount (x_talend_task_id);
create index Segment_x_talen_655897203 on Segment (x_talend_task_id);
create index Segment_x_talen_1142433852 on Segment (x_talend_staging_blockkey);
create index Segment_x_talen2083514564 on Segment (x_talend_staging_status);
create index SelfInfo_x_tale1568654002 on SelfInfo (x_talend_staging_status);
create index SelfInfo_x_tale_980081825 on SelfInfo (x_talend_task_id);
create index SelfInfo_x_tale_2002194894 on SelfInfo (x_talend_staging_blockkey);
create index ServiceProvider_1982435808 on ServiceProvider (x_talend_staging_status);
create index ServiceProvider1944040877 on ServiceProvider (x_talend_staging_blockkey);
create index ServiceProvider_1975711213 on ServiceProvider (x_talend_task_id);
create index ServiceRecipien1615861804 on ServiceRecipient (x_talend_staging_status);
create index ServiceRecipien1247371193 on ServiceRecipient (x_talend_staging_blockkey);
create index ServiceRecipien_2097634937 on ServiceRecipient (x_talend_task_id);
create index TALEND_TASK_EXE_1400335092 on TALEND_TASK_EXECUTION (x_talend_staging_blockkey);
create index TALEND_TASK_EXE1529315141 on TALEND_TASK_EXECUTION (x_talend_task_id);
create index TALEND_TASK_EXE519002124 on TALEND_TASK_EXECUTION (x_talend_staging_status);
create index UserAccountPart_1137517100 on UserAccount (x_talend_staging_blockkey);
create index UserAccountPart_1478095109 on UserAccount (x_talend_staging_status);
create index UserAccountPart_370840971 on UserAccount (x_talend_task_id);
create index WebsiteAddressA1855135049 on WebsiteAddress (x_talend_staging_blockkey);
create index WebsiteAddressA1185075305 on WebsiteAddress (x_talend_staging_status);
create index WebsiteAddressA_387984437 on WebsiteAddress (x_talend_task_id);
create index XRef_x_talend_s1423004700 on XRef (x_talend_staging_blockkey);
create index XRef_x_talend_task_id_index on XRef (x_talend_task_id);
create index XRef_x_talend_s897358620 on XRef (x_talend_staging_status);
alter table X_ANONYMOUS0_x__954682972 add constraint FKCDAE7AB913E74410 foreign key (x_talend_id) references X_ANONYMOUS0;
alter table X_ANONYMOUS0_x__954682972 add constraint FKCDAE7AB99C3CA8AD foreign key (x_externalrefer_373841693) references X_XRef_ExternalRefType;
create index X_Login_x_talen_655897203 on X_Login (x_talend_task_id);
create index X_Login_x_talen2083514564 on X_Login (x_talend_staging_status);
create index X_Login_x_talen_1142433852 on X_Login (x_talend_staging_blockkey);
create index X_Name_x_talend1263274152 on X_Name (x_talend_staging_blockkey);
create index X_Name_x_talend_task_id_index on X_Name (x_talend_task_id);
create index X_Name_x_talend_269286744 on X_Name (x_talend_staging_status);
