// ============================================================================
//
// Copyright (C) 2006-2012 Talend Inc. - www.talend.com
//
// This source code is available under agreement available at
// %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
//
// You should have received a copy of the agreement
// along with this program; if not, write to Talend SA
// 9 rue Pages 92150 Suresnes, France
//
// ============================================================================

/*
 * Generated by XDoclet - Do not edit!
 */
package org.talend.mdm.service.calljob.ejb.local;

public class CallJobServiceBeanSession
   extends org.talend.mdm.service.calljob.ejb.CallJobServiceBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
