// ============================================================================
//
// Copyright (C) 2006-2012 Talend Inc. - www.talend.com
//
// This source code is available under agreement available at
// %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
//
// You should have received a copy of the agreement
// along with this program; if not, write to Talend SA
// 9 rue Pages 92150 Suresnes, France
//
// ============================================================================

/*
 * Generated by XDoclet - Do not edit!
 */
package org.talend.mdm.service.calljob.ejb.local;

public interface CallJobServiceBeanLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CallJobServiceBeanLocal";
   public static final String JNDI_NAME="amalto/local/service/callJob";

   public org.talend.mdm.service.calljob.ejb.local.CallJobServiceBeanLocal create()
      throws javax.ejb.CreateException;

}
