/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.groovy.ejb.local;

/**
 * Local interface for GroovyPluginBean.
 * @xdoclet-generated at 18-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GroovyPluginBeanLocal
   extends javax.ejb.EJBLocalObject, com.amalto.core.objects.transformers.v2.util.TransformerPluginV2LocalInterface
{

}
