// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSDeleteItem {
    protected com.amalto.core.webservice.WSItemPK wsItemPK;
    protected java.lang.Boolean override;
    protected java.lang.Boolean withReport = false;
    protected java.lang.String source = ""; //$NON-NLS-1$
    protected java.lang.Boolean invokeBeforeDeleting = false;

    public WSDeleteItem() {
    }

    public WSDeleteItem(com.amalto.core.webservice.WSItemPK wsItemPK, java.lang.Boolean override) {
        this.wsItemPK = wsItemPK;
        this.override = override;
    }

    public com.amalto.core.webservice.WSItemPK getWsItemPK() {
        return wsItemPK;
    }

    public void setWsItemPK(com.amalto.core.webservice.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }

    public java.lang.Boolean getOverride() {
        return override;
    }

    public void setOverride(java.lang.Boolean override) {
        this.override = override;
    }

    public java.lang.Boolean getWithReport() {
        return withReport;
    }

    public void setWithReport(java.lang.Boolean withReport) {
        this.withReport = withReport;
    }

    public java.lang.String getSource() {
            return source;
        }

    public void setSource(java.lang.String source) {
        this.source = source;
    }

    public java.lang.Boolean getInvokeBeforeDeleting() {
            return invokeBeforeDeleting;
        }

    public void setInvokeBeforeDeleting(java.lang.Boolean invokeBeforeDeleting) {
        this.invokeBeforeDeleting = invokeBeforeDeleting;
    }
}
