// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSDeleteItemWithReport {
    protected com.amalto.core.webservice.WSItemPK wsItemPK;
    protected java.lang.String source;
    protected java.lang.String user;
    
    public WSDeleteItemWithReport() {
    }
    
    public WSDeleteItemWithReport(com.amalto.core.webservice.WSItemPK wsItemPK, java.lang.String source, java.lang.String user) {
        this.wsItemPK = wsItemPK;
        this.source = source;
        this.user = user;
    }
    
    public com.amalto.core.webservice.WSItemPK getWsItemPK() {
        return wsItemPK;
    }
    
    public void setWsItemPK(com.amalto.core.webservice.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }
    
    public java.lang.String getSource() {
        return source;
    }
    
    public void setSource(java.lang.String source) {
        this.source = source;
    }
    
    public java.lang.String getUser() {
        return user;
    }
    
    public void setUser(java.lang.String user) {
        this.user = user;
    }
}
