// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSDroppedItemPK {
    protected com.amalto.core.webservice.WSItemPK wsItemPK;
    protected java.lang.String partPath;

    public WSDroppedItemPK() {
    }
    
    public WSDroppedItemPK(WSItemPK wsItemPK, String partPath) {
        this.wsItemPK = wsItemPK;
        this.partPath = partPath;
    }
    
    public com.amalto.core.webservice.WSItemPK getWsItemPK() {
        return wsItemPK;
    }
    
    public void setWsItemPK(com.amalto.core.webservice.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }
    
    public java.lang.String getPartPath() {
        return partPath;
    }
    
    public void setPartPath(java.lang.String partPath) {
        this.partPath = partPath;
    }

}
