// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSExecuteStoredProcedure {
    protected com.amalto.core.webservice.WSStoredProcedurePK wsStoredProcedurePK;
    protected com.amalto.core.webservice.WSDataClusterPK wsDataClusterPK;
    protected java.lang.String[] parameters;
    
    public WSExecuteStoredProcedure() {
    }
    
    public WSExecuteStoredProcedure(WSStoredProcedurePK wsStoredProcedurePK, WSDataClusterPK wsDataClusterPK, String[] parameters) {
        this.wsStoredProcedurePK = wsStoredProcedurePK;
        this.wsDataClusterPK = wsDataClusterPK;
        this.parameters = parameters;
    }
    
    public com.amalto.core.webservice.WSStoredProcedurePK getWsStoredProcedurePK() {
        return wsStoredProcedurePK;
    }
    
    public void setWsStoredProcedurePK(com.amalto.core.webservice.WSStoredProcedurePK wsStoredProcedurePK) {
        this.wsStoredProcedurePK = wsStoredProcedurePK;
    }

    public com.amalto.core.webservice.WSDataClusterPK getWsDataClusterPK() {
        return wsDataClusterPK;
    }
    
    public void setWsDataClusterPK(com.amalto.core.webservice.WSDataClusterPK wsDataClusterPK) {
        this.wsDataClusterPK = wsDataClusterPK;
    }
    
    public java.lang.String[] getParameters() {
        return parameters;
    }
    
    public void setParameters(java.lang.String[] parameters) {
        this.parameters = parameters;
    }
}
