// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSFindChildrenItemsResult {
    protected com.amalto.core.webservice.WSStringArray wsStringArray;
    
    public WSFindChildrenItemsResult() {
    }
    
    public WSFindChildrenItemsResult(com.amalto.core.webservice.WSStringArray wsStringArray) {
        this.wsStringArray = wsStringArray;
    }
    
    public com.amalto.core.webservice.WSStringArray getWsStringArray() {
        return wsStringArray;
    }
    
    public void setWsStringArray(com.amalto.core.webservice.WSStringArray wsStringArray) {
        this.wsStringArray = wsStringArray;
    }
}
