// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSGetRoutingOrderV2ByCriteriaWithPaging {
    protected com.amalto.core.webservice.WSRoutingOrderV2SearchCriteriaWithPaging wsSearchCriteriaWithPaging;
    
    public WSGetRoutingOrderV2ByCriteriaWithPaging() {
    }
    
    public WSGetRoutingOrderV2ByCriteriaWithPaging(com.amalto.core.webservice.WSRoutingOrderV2SearchCriteriaWithPaging wsSearchCriteriaWithPaging) {
        this.wsSearchCriteriaWithPaging = wsSearchCriteriaWithPaging;
    }
    
    public com.amalto.core.webservice.WSRoutingOrderV2SearchCriteriaWithPaging getWsSearchCriteriaWithPaging() {
        return wsSearchCriteriaWithPaging;
    }
    
    public void setWsSearchCriteriaWithPaging(com.amalto.core.webservice.WSRoutingOrderV2SearchCriteriaWithPaging wsSearchCriteriaWithPaging) {
        this.wsSearchCriteriaWithPaging = wsSearchCriteriaWithPaging;
    }
}
