// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSGetLicense {
    protected com.amalto.core.webservice.WSLicensePK wsLicensePK;
    
    public WSGetLicense() {
    }
    
    public WSGetLicense(com.amalto.core.webservice.WSLicensePK wsLicensePK) {
        this.wsLicensePK = wsLicensePK;
    }
    
    public com.amalto.core.webservice.WSLicensePK getWsLicensePK() {
        return wsLicensePK;
    }
    
    public void setWsLicensePK(com.amalto.core.webservice.WSLicensePK wsLicensePK) {
        this.wsLicensePK = wsLicensePK;
    }
}
