// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutDBDataCluster {
    protected java.lang.String name;
    
    public WSPutDBDataCluster() {
    }
    
    public WSPutDBDataCluster(String name) {
        this.name = name;
    }

    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
}
