// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutLicense {
    protected com.amalto.core.webservice.WSLicense wsLicense;
    
    public WSPutLicense() {
    }
    
    public WSPutLicense(com.amalto.core.webservice.WSLicense wsLicense) {
        this.wsLicense = wsLicense;
    }
    
    public com.amalto.core.webservice.WSLicense getWsLicense() {
        return wsLicense;
    }
    
    public void setWsLicense(com.amalto.core.webservice.WSLicense wsLicense) {
        this.wsLicense = wsLicense;
    }
}
