// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutCustomForm {
    protected com.amalto.core.webservice.WSCustomForm wsCustomForm;
    
    public WSPutCustomForm() {
    }
    
    public WSPutCustomForm(com.amalto.core.webservice.WSCustomForm wsCustomForm) {
        this.wsCustomForm = wsCustomForm;
    }
    
    public com.amalto.core.webservice.WSCustomForm getWsCustomForm() {
        return wsCustomForm;
    }
    
    public void setWsCustomForm(com.amalto.core.webservice.WSCustomForm wsCustomForm) {
        this.wsCustomForm = wsCustomForm;
    }
}
