// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSUpdateMetadataItem {
    protected com.amalto.core.webservice.WSItemPK wsItemPK;
    protected java.lang.String taskId;
    
    public WSUpdateMetadataItem() {
    }
    
    public WSUpdateMetadataItem(com.amalto.core.webservice.WSItemPK wsItemPK, java.lang.String taskId) {
        this.wsItemPK = wsItemPK;
        this.taskId = taskId;
    }
    
    public com.amalto.core.webservice.WSItemPK getWsItemPK() {
        return wsItemPK;
    }
    
    public void setWsItemPK(com.amalto.core.webservice.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }
    
    public java.lang.String getTaskId() {
        return taskId;
    }
    
    public void setTaskId(java.lang.String taskId) {
        this.taskId = taskId;
    }
}
