// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSUpdateItemArrayMetadata {
    protected com.amalto.core.webservice.WSUpdateMetadataItem[] wsUpdateMetadataItem;
    
    public WSUpdateItemArrayMetadata() {
    }
    
    public WSUpdateItemArrayMetadata(com.amalto.core.webservice.WSUpdateMetadataItem[] wsUpdateMetadataItem) {
        this.wsUpdateMetadataItem = wsUpdateMetadataItem;
    }
    
    public com.amalto.core.webservice.WSUpdateMetadataItem[] getWsUpdateMetadataItem() {
        return wsUpdateMetadataItem;
    }
    
    public void setWsUpdateMetadataItem(com.amalto.core.webservice.WSUpdateMetadataItem[] wsUpdateMetadataItem) {
        this.wsUpdateMetadataItem = wsUpdateMetadataItem;
    }
}
