// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSVersioningHistoryEntry {
    protected java.lang.String tag;
    protected java.lang.String date;
    protected java.lang.String author;
    protected java.lang.String comments;
    
    public WSVersioningHistoryEntry() {
    }
    
    public WSVersioningHistoryEntry(String tag, String date, String author, String comments) {
        this.tag = tag;
        this.date = date;
        this.author = author;
        this.comments = comments;
    }
    
    public java.lang.String getTag() {
        return tag;
    }
    
    public void setTag(java.lang.String tag) {
        this.tag = tag;
    }
    
    public java.lang.String getDate() {
        return date;
    }
    
    public void setDate(java.lang.String date) {
        this.date = date;
    }
    
    public java.lang.String getAuthor() {
        return author;
    }
    
    public void setAuthor(java.lang.String author) {
        this.author = author;
    }
    
    public java.lang.String getComments() {
        return comments;
    }
    
    public void setComments(java.lang.String comments) {
        this.comments = comments;
    }
}
