// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSViewPK {
    protected java.lang.String pk;
    
    public WSViewPK() {
    }
    
    public WSViewPK(java.lang.String pk) {
        this.pk = pk;
    }
    
    public java.lang.String getPk() {
        return pk;
    }
    
    public void setPk(java.lang.String pk) {
        this.pk = pk;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof WSViewPK))
            return false;

        WSViewPK wsViewPK = (WSViewPK) o;

        if (pk != null ? !pk.equals(wsViewPK.pk) : wsViewPK.pk != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        return pk != null ? pk.hashCode() : 0;
    }
}
