// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;

public enum WSWhereOperator {
    JOIN,
    CONTAINS_TEXT_OF,
    CONTAINS,
    STARTSWITH,
    STRICTCONTAINS,
    EQUALS,
    NOT_EQUALS,
    GREATER_THAN,
    GREATER_THAN_OR_EQUAL,
    LOWER_THAN,
    LOWER_THAN_OR_EQUAL,
    NO_OPERATOR,
    FULLTEXTSEARCH,
    EMPTY_NULL;
}
