// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


import java.util.Arrays;

public class WSWhereAnd {
    protected com.amalto.core.webservice.WSWhereItem[] whereItems;
    
    public WSWhereAnd() {
    }
    
    public WSWhereAnd(com.amalto.core.webservice.WSWhereItem[] whereItems) {
        this.whereItems = whereItems;
    }
    
    public com.amalto.core.webservice.WSWhereItem[] getWhereItems() {
        return whereItems;
    }
    
    public void setWhereItems(com.amalto.core.webservice.WSWhereItem[] whereItems) {
        this.whereItems = whereItems;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof WSWhereAnd))
            return false;

        WSWhereAnd that = (WSWhereAnd) o;

        if (!Arrays.equals(whereItems, that.whereItems))
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        return whereItems != null ? Arrays.hashCode(whereItems) : 0;
    }
}
