// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, compilation edition R40)
// Generated source version: 1.1.2

package com.amalto.core.webservice;

import javax.xml.rpc.*;

public interface XtentisService extends javax.xml.rpc.Service {
    public XtentisPort getXtentisPort() throws ServiceException;
}
