// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSGetItemsByCustomFKFilters {
    protected com.amalto.webapp.util.webservices.WSDataClusterPK wsDataClusterPK;
    protected java.lang.String conceptName;
    protected com.amalto.webapp.util.webservices.WSStringArray viewablePaths;
    protected java.lang.String injectedXpath;
    protected int skip;
    protected int maxItems;
    protected java.lang.String orderBy;
    protected java.lang.String direction;
    protected boolean returnCount;
    protected com.amalto.webapp.util.webservices.WSWhereItem whereItem;

    public WSGetItemsByCustomFKFilters() {
    }
    
    public WSGetItemsByCustomFKFilters(WSDataClusterPK wsDataClusterPK, String conceptName, WSStringArray viewablePaths, String injectedXpath, int skip, int maxItems, String orderBy, String direction, boolean returnCount, com.amalto.webapp.util.webservices.WSWhereItem whereItem) {
        this.wsDataClusterPK = wsDataClusterPK;
        this.conceptName = conceptName;
        this.viewablePaths = viewablePaths;
        this.injectedXpath = injectedXpath;
        this.skip = skip;
        this.maxItems = maxItems;
        this.orderBy = orderBy;
        this.direction = direction;
        this.returnCount = returnCount;
        this.whereItem = whereItem;
    }
    
    public com.amalto.webapp.util.webservices.WSDataClusterPK getWsDataClusterPK() {
        return wsDataClusterPK;
    }
    
    public void setWsDataClusterPK(com.amalto.webapp.util.webservices.WSDataClusterPK wsDataClusterPK) {
        this.wsDataClusterPK = wsDataClusterPK;
    }
    
    public java.lang.String getConceptName() {
        return conceptName;
    }
    
    public void setConceptName(java.lang.String conceptName) {
        this.conceptName = conceptName;
    }
    
    public com.amalto.webapp.util.webservices.WSStringArray getViewablePaths() {
        return viewablePaths;
    }
    
    public void setViewablePaths(com.amalto.webapp.util.webservices.WSStringArray viewablePaths) {
        this.viewablePaths = viewablePaths;
    }
    
    public java.lang.String getInjectedXpath() {
        return injectedXpath;
    }
    
    public void setInjectedXpath(java.lang.String injectedXpath) {
        this.injectedXpath = injectedXpath;
    }
    
    public int getSkip() {
        return skip;
    }
    
    public void setSkip(int skip) {
        this.skip = skip;
    }
    
    public int getMaxItems() {
        return maxItems;
    }
    
    public void setMaxItems(int maxItems) {
        this.maxItems = maxItems;
    }
    
    public java.lang.String getOrderBy() {
        return orderBy;
    }
    
    public void setOrderBy(java.lang.String orderBy) {
        this.orderBy = orderBy;
    }
    
    public java.lang.String getDirection() {
        return direction;
    }
    
    public void setDirection(java.lang.String direction) {
        this.direction = direction;
    }

    public boolean getReturnCount() {
        return returnCount;
    }

    public void setReturnCount(boolean returnCount) {
        this.returnCount = returnCount;
    }

    public com.amalto.webapp.util.webservices.WSWhereItem getWhereItem() {
        return whereItem;
    }

    public void setWhereItem(com.amalto.webapp.util.webservices.WSWhereItem whereItem) {
        this.whereItem = whereItem;
    }
}
