// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSMenuEntry {
    protected java.lang.String id;
    protected com.amalto.webapp.util.webservices.WSMenuMenuEntriesDescriptions[] descriptions;
    protected java.lang.String context;
    protected java.lang.String application;
    protected java.lang.String icon;
    protected com.amalto.webapp.util.webservices.WSMenuEntry[] subMenus;
    
    public WSMenuEntry() {
    }
    
    public WSMenuEntry(java.lang.String id, com.amalto.webapp.util.webservices.WSMenuMenuEntriesDescriptions[] descriptions, java.lang.String context, java.lang.String application, java.lang.String icon, com.amalto.webapp.util.webservices.WSMenuEntry[] subMenus) {
        this.id = id;
        this.descriptions = descriptions;
        this.context = context;
        this.application = application;
        this.icon = icon;
        this.subMenus = subMenus;
    }
    
    public java.lang.String getId() {
        return id;
    }
    
    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public com.amalto.webapp.util.webservices.WSMenuMenuEntriesDescriptions[] getDescriptions() {
        return descriptions;
    }
    
    public void setDescriptions(com.amalto.webapp.util.webservices.WSMenuMenuEntriesDescriptions[] descriptions) {
        this.descriptions = descriptions;
    }
    
    public java.lang.String getContext() {
        return context;
    }
    
    public void setContext(java.lang.String context) {
        this.context = context;
    }
    
    public java.lang.String getApplication() {
        return application;
    }
    
    public void setApplication(java.lang.String application) {
        this.application = application;
    }
    
    public java.lang.String getIcon() {
        return icon;
    }
    
    public void setIcon(java.lang.String icon) {
        this.icon = icon;
    }
    
    public com.amalto.webapp.util.webservices.WSMenuEntry[] getSubMenus() {
        return subMenus;
    }
    
    public void setSubMenus(com.amalto.webapp.util.webservices.WSMenuEntry[] subMenus) {
        this.subMenus = subMenus;
    }
}
