// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSProcessTaskInstanceArray {
    protected com.amalto.webapp.util.webservices.WSProcessTaskInstance[] wstaskinstance;
    
    public WSProcessTaskInstanceArray() {
    }
    
    public WSProcessTaskInstanceArray(com.amalto.webapp.util.webservices.WSProcessTaskInstance[] wstaskinstance) {
        this.wstaskinstance = wstaskinstance;
    }
    
    public com.amalto.webapp.util.webservices.WSProcessTaskInstance[] getWstaskinstance() {
        return wstaskinstance;
    }
    
    public void setWstaskinstance(com.amalto.webapp.util.webservices.WSProcessTaskInstance[] wstaskinstance) {
        this.wstaskinstance = wstaskinstance;
    }
}
