// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSUpdateItemArrayMetadata {
    protected com.amalto.webapp.util.webservices.WSUpdateMetadataItem[] wsUpdateMetadataItem;
    
    public WSUpdateItemArrayMetadata() {
    }
    
    public WSUpdateItemArrayMetadata(com.amalto.webapp.util.webservices.WSUpdateMetadataItem[] wsUpdateMetadataItem) {
        this.wsUpdateMetadataItem = wsUpdateMetadataItem;
    }
    
    public com.amalto.webapp.util.webservices.WSUpdateMetadataItem[] getWsUpdateMetadataItem() {
        return wsUpdateMetadataItem;
    }
    
    public void setWsUpdateMetadataItem(com.amalto.webapp.util.webservices.WSUpdateMetadataItem[] wsUpdateMetadataItem) {
        this.wsUpdateMetadataItem = wsUpdateMetadataItem;
    }
}
