// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSWorkflowUnDeploy {
    protected com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID uuid;
    
    public WSWorkflowUnDeploy() {
    }
    
    public WSWorkflowUnDeploy(com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID uuid) {
        this.uuid = uuid;
    }
    
    public com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID getUuid() {
        return uuid;
    }
    
    public void setUuid(com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID uuid) {
        this.uuid = uuid;
    }
}
