// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSAssignTask {
    protected java.lang.String taskUUID;
    protected com.amalto.webapp.util.webservices.WSStringArray candicates;
    
    public WSAssignTask() {
    }
    
    public WSAssignTask(java.lang.String taskUUID, com.amalto.webapp.util.webservices.WSStringArray candicates) {
        this.taskUUID = taskUUID;
        this.candicates = candicates;
    }
    
    public java.lang.String getTaskUUID() {
        return taskUUID;
    }
    
    public void setTaskUUID(java.lang.String taskUUID) {
        this.taskUUID = taskUUID;
    }
    
    public com.amalto.webapp.util.webservices.WSStringArray getCandicates() {
        return candicates;
    }
    
    public void setCandicates(com.amalto.webapp.util.webservices.WSStringArray candicates) {
        this.candicates = candicates;
    }
}
