// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSAutoIncrement {
    protected java.lang.String autoincrement;
    
    public WSAutoIncrement() {
    }
    
    public WSAutoIncrement(java.lang.String autoincrement) {
        this.autoincrement = autoincrement;
    }
    
    public java.lang.String getAutoincrement() {
        return autoincrement;
    }
    
    public void setAutoincrement(java.lang.String autoincrement) {
        this.autoincrement = autoincrement;
    }
}
