// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSCategoryData {
    protected java.lang.String categorySchema;
    
    public WSCategoryData() {
    }
    
    public WSCategoryData(java.lang.String categorySchema) {
        this.categorySchema = categorySchema;
    }
    
    public java.lang.String getCategorySchema() {
        return categorySchema;
    }
    
    public void setCategorySchema(java.lang.String categorySchema) {
        this.categorySchema = categorySchema;
    }
}
