// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation ��1.1.2_01������� R40��
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSDeleteItem {
    protected com.amalto.webapp.util.webservices.WSItemPK wsItemPK;

    private boolean override;

    public WSDeleteItem() {
    }
    
    public WSDeleteItem(com.amalto.webapp.util.webservices.WSItemPK wsItemPK, boolean isOverride) {
        this.wsItemPK = wsItemPK;
        override = isOverride;
    }

    public com.amalto.webapp.util.webservices.WSItemPK getWsItemPK() {
        return wsItemPK;
    }
    
    public void setWsItemPK(com.amalto.webapp.util.webservices.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }

    public boolean isOverride() {
        return override;
    }

    public void setOverride(boolean override) {
        this.override = override;
    }
}
