// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSGetItemPKsByFullCriteria {
    protected com.amalto.webapp.util.webservices.WSGetItemPKsByCriteria wsGetItemPKsByCriteria;
    protected boolean useFTSearch;
    
    public WSGetItemPKsByFullCriteria() {
    }
    
    public WSGetItemPKsByFullCriteria(com.amalto.webapp.util.webservices.WSGetItemPKsByCriteria wsGetItemPKsByCriteria, boolean useFTSearch) {
        this.wsGetItemPKsByCriteria = wsGetItemPKsByCriteria;
        this.useFTSearch = useFTSearch;
    }
    
    public com.amalto.webapp.util.webservices.WSGetItemPKsByCriteria getWsGetItemPKsByCriteria() {
        return wsGetItemPKsByCriteria;
    }
    
    public void setWsGetItemPKsByCriteria(com.amalto.webapp.util.webservices.WSGetItemPKsByCriteria wsGetItemPKsByCriteria) {
        this.wsGetItemPKsByCriteria = wsGetItemPKsByCriteria;
    }
    
    public boolean isUseFTSearch() {
        return useFTSearch;
    }
    
    public void setUseFTSearch(boolean useFTSearch) {
        this.useFTSearch = useFTSearch;
    }
}
