// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSGetChildrenItems {
    protected java.lang.String clusterName;
    protected java.lang.String conceptName;
    protected com.amalto.webapp.util.webservices.WSStringArray PKXpaths;
    protected java.lang.String FKXpath;
    protected java.lang.String labelXpath;
    protected java.lang.String fatherPK;
    protected com.amalto.webapp.util.webservices.WSWhereItem whereItem;
    protected int start;
    protected int limit;
    
    public WSGetChildrenItems() {
    }
    
    public WSGetChildrenItems(java.lang.String clusterName, java.lang.String conceptName, com.amalto.webapp.util.webservices.WSStringArray PKXpaths, java.lang.String FKXpath, java.lang.String labelXpath, java.lang.String fatherPK, com.amalto.webapp.util.webservices.WSWhereItem whereItem, int start, int limit) {
        this.clusterName = clusterName;
        this.conceptName = conceptName;
        this.PKXpaths = PKXpaths;
        this.FKXpath = FKXpath;
        this.labelXpath = labelXpath;
        this.fatherPK = fatherPK;
        this.whereItem = whereItem;
        this.start = start;
        this.limit = limit;
    }
    
    public java.lang.String getClusterName() {
        return clusterName;
    }
    
    public void setClusterName(java.lang.String clusterName) {
        this.clusterName = clusterName;
    }
    
    public java.lang.String getConceptName() {
        return conceptName;
    }
    
    public void setConceptName(java.lang.String conceptName) {
        this.conceptName = conceptName;
    }
    
    public com.amalto.webapp.util.webservices.WSStringArray getPKXpaths() {
        return PKXpaths;
    }
    
    public void setPKXpaths(com.amalto.webapp.util.webservices.WSStringArray PKXpaths) {
        this.PKXpaths = PKXpaths;
    }
    
    public java.lang.String getFKXpath() {
        return FKXpath;
    }
    
    public void setFKXpath(java.lang.String FKXpath) {
        this.FKXpath = FKXpath;
    }
    
    public java.lang.String getLabelXpath() {
        return labelXpath;
    }
    
    public void setLabelXpath(java.lang.String labelXpath) {
        this.labelXpath = labelXpath;
    }
    
    public java.lang.String getFatherPK() {
        return fatherPK;
    }
    
    public void setFatherPK(java.lang.String fatherPK) {
        this.fatherPK = fatherPK;
    }
    
    public com.amalto.webapp.util.webservices.WSWhereItem getWhereItem() {
        return whereItem;
    }
    
    public void setWhereItem(com.amalto.webapp.util.webservices.WSWhereItem whereItem) {
        this.whereItem = whereItem;
    }
    
    public int getStart() {
        return start;
    }
    
    public void setStart(int start) {
        this.start = start;
    }
    
    public int getLimit() {
        return limit;
    }
    
    public void setLimit(int limit) {
        this.limit = limit;
    }
}
