// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSHashMap {
    protected com.amalto.webapp.util.webservices.WSStartProcessInstanceVariableEntry[] entry;
    
    public WSHashMap() {
    }
    
    public WSHashMap(com.amalto.webapp.util.webservices.WSStartProcessInstanceVariableEntry[] entry) {
        this.entry = entry;
    }
    
    public com.amalto.webapp.util.webservices.WSStartProcessInstanceVariableEntry[] getEntry() {
        return entry;
    }
    
    public void setEntry(com.amalto.webapp.util.webservices.WSStartProcessInstanceVariableEntry[] entry) {
        this.entry = entry;
    }
}
