// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSIsItemModifiedByOther {
    protected com.amalto.webapp.util.webservices.WSItem wsItem;
    
    public WSIsItemModifiedByOther() {
    }
    
    public WSIsItemModifiedByOther(com.amalto.webapp.util.webservices.WSItem wsItem) {
        this.wsItem = wsItem;
    }
    
    public com.amalto.webapp.util.webservices.WSItem getWsItem() {
        return wsItem;
    }
    
    public void setWsItem(com.amalto.webapp.util.webservices.WSItem wsItem) {
        this.wsItem = wsItem;
    }
}
