// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSLicense {
    protected java.lang.String license;
    protected java.lang.String customerCompany;
    
    public WSLicense() {
    }
    
    public WSLicense(java.lang.String license, java.lang.String customerCompany) {
        this.license = license;
        this.customerCompany = customerCompany;
    }
    
    public java.lang.String getLicense() {
        return license;
    }
    
    public void setLicense(java.lang.String license) {
        this.license = license;
    }
    
    public java.lang.String getCustomerCompany() {
        return customerCompany;
    }
    
    public void setCustomerCompany(java.lang.String customerCompany) {
        this.customerCompany = customerCompany;
    }
}
