// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSMDMJobArray {
    protected com.amalto.webapp.util.webservices.WSMDMJob[] wsMDMJob;
    
    public WSMDMJobArray() {
    }
    
    public WSMDMJobArray(com.amalto.webapp.util.webservices.WSMDMJob[] wsMDMJob) {
        this.wsMDMJob = wsMDMJob;
    }
    
    public com.amalto.webapp.util.webservices.WSMDMJob[] getWsMDMJob() {
        return wsMDMJob;
    }
    
    public void setWsMDMJob(com.amalto.webapp.util.webservices.WSMDMJob[] wsMDMJob) {
        this.wsMDMJob = wsMDMJob;
    }
}
