// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSProcessInstanceArray {
    protected com.amalto.webapp.util.webservices.WSProcessInstance[] instance;
    
    public WSProcessInstanceArray() {
    }
    
    public WSProcessInstanceArray(com.amalto.webapp.util.webservices.WSProcessInstance[] instance) {
        this.instance = instance;
    }
    
    public com.amalto.webapp.util.webservices.WSProcessInstance[] getInstance() {
        return instance;
    }
    
    public void setInstance(com.amalto.webapp.util.webservices.WSProcessInstance[] instance) {
        this.instance = instance;
    }
}
