// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSPutLicense {
    protected com.amalto.webapp.util.webservices.WSLicense wsLicense;
    
    public WSPutLicense() {
    }
    
    public WSPutLicense(com.amalto.webapp.util.webservices.WSLicense wsLicense) {
        this.wsLicense = wsLicense;
    }
    
    public com.amalto.webapp.util.webservices.WSLicense getWsLicense() {
        return wsLicense;
    }
    
    public void setWsLicense(com.amalto.webapp.util.webservices.WSLicense wsLicense) {
        this.wsLicense = wsLicense;
    }
}
