// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSPutItemByOperatorType {
    protected com.amalto.webapp.util.webservices.WSDataClusterPK wsDataClusterPK;
    protected java.lang.String xmlString;
    protected com.amalto.webapp.util.webservices.WSDataModelPK wsDataModelPK;
    protected com.amalto.webapp.util.webservices.WSOperatorType operatortype;
    
    public WSPutItemByOperatorType() {
    }
    
    public WSPutItemByOperatorType(com.amalto.webapp.util.webservices.WSDataClusterPK wsDataClusterPK, java.lang.String xmlString, com.amalto.webapp.util.webservices.WSDataModelPK wsDataModelPK, com.amalto.webapp.util.webservices.WSOperatorType operatortype) {
        this.wsDataClusterPK = wsDataClusterPK;
        this.xmlString = xmlString;
        this.wsDataModelPK = wsDataModelPK;
        this.operatortype = operatortype;
    }
    
    public com.amalto.webapp.util.webservices.WSDataClusterPK getWsDataClusterPK() {
        return wsDataClusterPK;
    }
    
    public void setWsDataClusterPK(com.amalto.webapp.util.webservices.WSDataClusterPK wsDataClusterPK) {
        this.wsDataClusterPK = wsDataClusterPK;
    }
    
    public java.lang.String getXmlString() {
        return xmlString;
    }
    
    public void setXmlString(java.lang.String xmlString) {
        this.xmlString = xmlString;
    }
    
    public com.amalto.webapp.util.webservices.WSDataModelPK getWsDataModelPK() {
        return wsDataModelPK;
    }
    
    public void setWsDataModelPK(com.amalto.webapp.util.webservices.WSDataModelPK wsDataModelPK) {
        this.wsDataModelPK = wsDataModelPK;
    }
    
    public com.amalto.webapp.util.webservices.WSOperatorType getOperatortype() {
        return operatortype;
    }
    
    public void setOperatortype(com.amalto.webapp.util.webservices.WSOperatorType operatortype) {
        this.operatortype = operatortype;
    }
}
