// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSPutItemWithCustomReport {
    protected com.amalto.webapp.util.webservices.WSPutItemWithReport wsPutItemWithReport;
    protected java.lang.String user;
    
    public WSPutItemWithCustomReport() {
    }
    
    public WSPutItemWithCustomReport(com.amalto.webapp.util.webservices.WSPutItemWithReport wsPutItemWithReport, java.lang.String user) {
        this.wsPutItemWithReport = wsPutItemWithReport;
        this.user = user;
    }
    
    public com.amalto.webapp.util.webservices.WSPutItemWithReport getWsPutItemWithReport() {
        return wsPutItemWithReport;
    }
    
    public void setWsPutItemWithReport(com.amalto.webapp.util.webservices.WSPutItemWithReport wsPutItemWithReport) {
        this.wsPutItemWithReport = wsPutItemWithReport;
    }
    
    public java.lang.String getUser() {
        return user;
    }
    
    public void setUser(java.lang.String user) {
        this.user = user;
    }
}
