// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSStartProcessInstance {
    protected com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID processUUID;
    protected com.amalto.webapp.util.webservices.WSHashMap variable;
    
    public WSStartProcessInstance() {
    }
    
    public WSStartProcessInstance(com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID processUUID, com.amalto.webapp.util.webservices.WSHashMap variable) {
        this.processUUID = processUUID;
        this.variable = variable;
    }
    
    public com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID getProcessUUID() {
        return processUUID;
    }
    
    public void setProcessUUID(com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID processUUID) {
        this.processUUID = processUUID;
    }
    
    public com.amalto.webapp.util.webservices.WSHashMap getVariable() {
        return variable;
    }
    
    public void setVariable(com.amalto.webapp.util.webservices.WSHashMap variable) {
        this.variable = variable;
    }
}
