// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSUnassignTask {
    protected java.lang.String taskUUID;
    
    public WSUnassignTask() {
    }
    
    public WSUnassignTask(java.lang.String taskUUID) {
        this.taskUUID = taskUUID;
    }
    
    public java.lang.String getTaskUUID() {
        return taskUUID;
    }
    
    public void setTaskUUID(java.lang.String taskUUID) {
        this.taskUUID = taskUUID;
    }
}
