// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSVersion {
    protected int major;
    protected int minor;
    protected int revision;
    protected java.lang.String build;
    protected java.lang.String description;
    protected java.lang.String date;
    
    public WSVersion() {
    }
    
    public WSVersion(int major, int minor, int revision, java.lang.String build, java.lang.String description, java.lang.String date) {
        this.major = major;
        this.minor = minor;
        this.revision = revision;
        this.build = build;
        this.description = description;
        this.date = date;
    }
    
    public int getMajor() {
        return major;
    }
    
    public void setMajor(int major) {
        this.major = major;
    }
    
    public int getMinor() {
        return minor;
    }
    
    public void setMinor(int minor) {
        this.minor = minor;
    }
    
    public int getRevision() {
        return revision;
    }
    
    public void setRevision(int revision) {
        this.revision = revision;
    }
    
    public java.lang.String getBuild() {
        return build;
    }
    
    public void setBuild(java.lang.String build) {
        this.build = build;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getDate() {
        return date;
    }
    
    public void setDate(java.lang.String date) {
        this.date = date;
    }
}
