// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSViewPK {
    protected java.lang.String pk;
    
    public WSViewPK() {
    }
    
    public WSViewPK(java.lang.String pk) {
        this.pk = pk;
    }
    
    public java.lang.String getPk() {
        return pk;
    }
    
    public void setPk(java.lang.String pk) {
        this.pk = pk;
    }

    @Override
    public boolean equals(Object obj) {
        if (super.equals(obj))
            return true;
        if (obj == null)
            return false;
        if (obj instanceof WSViewPK) {
            WSViewPK another = (WSViewPK) obj;
            if (pk != null) {
                return pk.equals(another.getPk());
            } else {
                return pk == another.getPk();
            }
        } else {
            return false;
        }
    }
}
