// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSView {
    protected java.lang.String name;
    protected java.lang.String description;
    protected java.lang.String[] viewableBusinessElements;
    protected com.amalto.webapp.util.webservices.WSWhereCondition[] whereConditions;
    protected java.lang.String[] searchableBusinessElements;
    protected java.lang.String transformerPK;
    protected com.amalto.webapp.util.webservices.WSBoolean isTransformerActive;
    
    public WSView() {
    }
    
    public WSView(java.lang.String name, java.lang.String description, java.lang.String[] viewableBusinessElements, com.amalto.webapp.util.webservices.WSWhereCondition[] whereConditions, java.lang.String[] searchableBusinessElements, java.lang.String transformerPK, com.amalto.webapp.util.webservices.WSBoolean isTransformerActive) {
        this.name = name;
        this.description = description;
        this.viewableBusinessElements = viewableBusinessElements;
        this.whereConditions = whereConditions;
        this.searchableBusinessElements = searchableBusinessElements;
        this.transformerPK = transformerPK;
        this.isTransformerActive = isTransformerActive;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String[] getViewableBusinessElements() {
        return viewableBusinessElements;
    }
    
    public void setViewableBusinessElements(java.lang.String[] viewableBusinessElements) {
        this.viewableBusinessElements = viewableBusinessElements;
    }
    
    public com.amalto.webapp.util.webservices.WSWhereCondition[] getWhereConditions() {
        return whereConditions;
    }
    
    public void setWhereConditions(com.amalto.webapp.util.webservices.WSWhereCondition[] whereConditions) {
        this.whereConditions = whereConditions;
    }
    
    public java.lang.String[] getSearchableBusinessElements() {
        return searchableBusinessElements;
    }
    
    public void setSearchableBusinessElements(java.lang.String[] searchableBusinessElements) {
        this.searchableBusinessElements = searchableBusinessElements;
    }
    
    public java.lang.String getTransformerPK() {
        return transformerPK;
    }
    
    public void setTransformerPK(java.lang.String transformerPK) {
        this.transformerPK = transformerPK;
    }
    
    public com.amalto.webapp.util.webservices.WSBoolean getIsTransformerActive() {
        return isTransformerActive;
    }
    
    public void setIsTransformerActive(com.amalto.webapp.util.webservices.WSBoolean isTransformerActive) {
        this.isTransformerActive = isTransformerActive;
    }
}
