// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSWorkflowDeleteProcessInstancesRequest {
    protected java.lang.String processName;
    
    public WSWorkflowDeleteProcessInstancesRequest() {
    }
    
    public WSWorkflowDeleteProcessInstancesRequest(java.lang.String processName) {
        this.processName = processName;
    }
    
    public java.lang.String getProcessName() {
        return processName;
    }
    
    public void setProcessName(java.lang.String processName) {
        this.processName = processName;
    }
}
