// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSWorkflowDeploy {
    protected java.lang.String filename;
    
    public WSWorkflowDeploy() {
    }
    
    public WSWorkflowDeploy(java.lang.String filename) {
        this.filename = filename;
    }
    
    public java.lang.String getFilename() {
        return filename;
    }
    
    public void setFilename(java.lang.String filename) {
        this.filename = filename;
    }
}
