// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSWorkflowProcessDefinitionUUIDArray {
    protected com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID[] wsWorkflowProcessDefinitions;
    
    public WSWorkflowProcessDefinitionUUIDArray() {
    }
    
    public WSWorkflowProcessDefinitionUUIDArray(com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID[] wsWorkflowProcessDefinitions) {
        this.wsWorkflowProcessDefinitions = wsWorkflowProcessDefinitions;
    }
    
    public com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID[] getWsWorkflowProcessDefinitions() {
        return wsWorkflowProcessDefinitions;
    }
    
    public void setWsWorkflowProcessDefinitions(com.amalto.webapp.util.webservices.WSWorkflowProcessDefinitionUUID[] wsWorkflowProcessDefinitions) {
        this.wsWorkflowProcessDefinitions = wsWorkflowProcessDefinitions;
    }
}
