// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation 
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSWorkflowGetTaskList {
    protected java.lang.String processinstanceuuid;
    
    public WSWorkflowGetTaskList() {
    }
    
    public WSWorkflowGetTaskList(java.lang.String processinstanceuuid) {
        this.processinstanceuuid = processinstanceuuid;
    }
    
    public java.lang.String getProcessinstanceuuid() {
        return processinstanceuuid;
    }
    
    public void setProcessinstanceuuid(java.lang.String processinstanceuuid) {
        this.processinstanceuuid = processinstanceuuid;
    }
}
