/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.mimecontent.ejb.local;

/**
 * Local home interface for MIMEContentPlugin.
 * @xdoclet-generated at 18-02-11
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MIMEContentPluginLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MIMEContentPluginLocal";
   public static final String JNDI_NAME="amalto/local/transformer/plugin/mime";

   public com.amalto.core.plugin.base.mimecontent.ejb.local.MIMEContentPluginLocal create()
      throws javax.ejb.CreateException;

}
