/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.mimecontent.ejb.local;

/**
 * Local interface for MIMEContentPlugin.
 * @xdoclet-generated at 18-02-11
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MIMEContentPluginLocal
   extends javax.ejb.EJBLocalObject, com.amalto.core.objects.transformers.v2.util.TransformerPluginV2LocalInterface
{

}
