/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.dumpandgo.ejb.local;

/**
 * Local interface for DumpAndGoPlugin.
 * @xdoclet-generated at 18-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface DumpAndGoPluginLocal
   extends javax.ejb.EJBLocalObject, com.amalto.core.objects.transformers.v2.util.TransformerPluginV2LocalInterface
{

}
