/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.customform.ejb.remote;

/**
 * Home interface for CustomFormCtrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CustomFormCtrlHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CustomFormCtrl";
   public static final String JNDI_NAME="amalto/remote/core/customformctrl";

   public com.amalto.core.objects.customform.ejb.remote.CustomFormCtrl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
