/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.customform.ejb.remote;

/**
 * Remote interface for CustomFormCtrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CustomFormCtrl
   extends javax.ejb.EJBObject
{
   /**
    * Creates or updates a CustomForm
    * @throws XtentisException
    */
   public com.amalto.core.objects.customform.ejb.CustomFormPOJOPK putCustomForm( com.amalto.core.objects.customform.ejb.CustomFormPOJO customForm )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Get CustomForm
    * @throws XtentisException
    */
   public com.amalto.core.objects.customform.ejb.CustomFormPOJO getCustomForm( com.amalto.core.objects.customform.ejb.CustomFormPOJOPK pk )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Get CustomForm according to the current user's role
    * @throws XtentisException
    */
   public com.amalto.core.objects.customform.ejb.CustomFormPOJO getUserCustomForm( com.amalto.core.objects.customform.ejb.CustomFormPOJOPK cpk )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Get a CustomForm - no exception is thrown: returns null if not found
    * @throws XtentisException
    */
   public com.amalto.core.objects.customform.ejb.CustomFormPOJO existsCustomForm( com.amalto.core.objects.customform.ejb.CustomFormPOJOPK pk )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Remove an item
    * @throws XtentisException
    */
   public com.amalto.core.objects.customform.ejb.CustomFormPOJOPK removeCustomForm( com.amalto.core.objects.customform.ejb.CustomFormPOJOPK pk )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Retrieve all CustomForm PKS
    * @throws XtentisException
    */
   public java.util.Collection getCustomFormPKs( java.lang.String regex )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

}
