
// ============================================================================
//
// Copyright (C) 2006-2014 Talend Inc. - www.talend.com
//
// This source code is available under agreement available at
// %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
//
// You should have received a copy of the agreement
// along with this program; if not, write to Talend SA
// 9 rue Pages 92150 Suresnes, France
//
// ============================================================================

package org.talend.mdm.service.calljob.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSxml", targetNamespace = "http://talend.org")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WSxml {


    /**
     * 
     * @param args
     * @return
     *     returns talend.core.transformer.plugin.v2.tiscall.webservices.RunJobReturn
     */
    @WebMethod
    @WebResult(name = "runJobReturn", targetNamespace = "http://talend.org", partName = "runJobReturn")
    public RunJobReturn runJob(
        @WebParam(name = "args", targetNamespace = "http://talend.org", partName = "args")
        Args args);

}
