 /*
 * Generated by XDoclet - Do not edit!
 * this class was prodiuced by xdoclet automagically...
 */
package com.amalto.core.objects.customform.ejb.remote;

import java.util.*;

/**
 * This class is remote adapter to CustomFormCtrl. It provides convenient way to access
 * facade session bean. Inverit from this class to provide reasonable caching and event handling capabilities.
 *
 * Remote facade for CustomFormCtrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */

public class CustomFormCtrlRemote extends Observable
{
    static CustomFormCtrlRemote _instance = null;
    public static CustomFormCtrlRemote getInstance() {
        if(_instance == null) {
	   _instance = new CustomFormCtrlRemote();
	}
	return _instance;
    }

  /**
   * cached remote session interface
   */
  com.amalto.core.objects.customform.ejb.remote.CustomFormCtrl _session = null;
  /**
   * return session bean remote interface
   */
   protected com.amalto.core.objects.customform.ejb.remote.CustomFormCtrl getSession() {
      try {
   	if(_session == null) {
	   _session = com.amalto.core.objects.customform.ejb.local.CustomFormCtrlUtil.getHome().create();
	}
	return _session;
      } catch(Exception ex) {
        // just catch it here and return null.
        // somebody can provide better solution
	ex.printStackTrace();
	return null;
      }
   }

   public com.amalto.core.objects.customform.ejb.CustomFormPOJOPK putCustomForm ( com.amalto.core.objects.customform.ejb.CustomFormPOJO customForm )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.objects.customform.ejb.CustomFormPOJOPK retval;
       retval =  getSession().putCustomForm( customForm );

      return retval;

   }

   public com.amalto.core.objects.customform.ejb.CustomFormPOJO getCustomForm ( com.amalto.core.objects.customform.ejb.CustomFormPOJOPK pk )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.objects.customform.ejb.CustomFormPOJO retval;
       retval =  getSession().getCustomForm( pk );

      return retval;

   }

   public com.amalto.core.objects.customform.ejb.CustomFormPOJO getUserCustomForm ( com.amalto.core.objects.customform.ejb.CustomFormPOJOPK cpk )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.objects.customform.ejb.CustomFormPOJO retval;
       retval =  getSession().getUserCustomForm( cpk );

      return retval;

   }

   public com.amalto.core.objects.customform.ejb.CustomFormPOJO existsCustomForm ( com.amalto.core.objects.customform.ejb.CustomFormPOJOPK pk )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.objects.customform.ejb.CustomFormPOJO retval;
       retval =  getSession().existsCustomForm( pk );

      return retval;

   }

   public com.amalto.core.objects.customform.ejb.CustomFormPOJOPK removeCustomForm ( com.amalto.core.objects.customform.ejb.CustomFormPOJOPK pk )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.objects.customform.ejb.CustomFormPOJOPK retval;
       retval =  getSession().removeCustomForm( pk );

      return retval;

   }

   public java.util.Collection getCustomFormPKs ( java.lang.String regex )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.Collection retval;
       retval =  getSession().getCustomFormPKs( regex );

      return retval;

   }

  /**
   * override this method to provide feedback to interested objects
   * in case collections were changed.
   */
  public void invalidate() {

  	setChanged();
	notifyObservers();
  }
}
