// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSExistsCustomForm {
    protected com.amalto.core.webservice.WSCustomFormPK wsCustomFormPK;
    
    public WSExistsCustomForm() {
    }
    
    public WSExistsCustomForm(com.amalto.core.webservice.WSCustomFormPK wsCustomFormPK) {
        this.wsCustomFormPK = wsCustomFormPK;
    }
    
    public com.amalto.core.webservice.WSCustomFormPK getWsCustomFormPK() {
        return wsCustomFormPK;
    }
    
    public void setWsCustomFormPK(com.amalto.core.webservice.WSCustomFormPK wsCustomFormPK) {
        this.wsCustomFormPK = wsCustomFormPK;
    }
}
