// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation （1.1.2_01，编译版 R40）
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutItemByOperatorType {
    protected com.amalto.core.webservice.WSDataClusterPK wsDataClusterPK;
    protected java.lang.String xmlString;
    protected com.amalto.core.webservice.WSDataModelPK wsDataModelPK;
    protected com.amalto.core.webservice.WSOperatorType operatortype;
    
    public WSPutItemByOperatorType() {
    }
    
    public WSPutItemByOperatorType(com.amalto.core.webservice.WSDataClusterPK wsDataClusterPK, java.lang.String xmlString, com.amalto.core.webservice.WSDataModelPK wsDataModelPK, com.amalto.core.webservice.WSOperatorType operatortype) {
        this.wsDataClusterPK = wsDataClusterPK;
        this.xmlString = xmlString;
        this.wsDataModelPK = wsDataModelPK;
        this.operatortype = operatortype;
    }
    
    public com.amalto.core.webservice.WSDataClusterPK getWsDataClusterPK() {
        return wsDataClusterPK;
    }
    
    public void setWsDataClusterPK(com.amalto.core.webservice.WSDataClusterPK wsDataClusterPK) {
        this.wsDataClusterPK = wsDataClusterPK;
    }
    
    public java.lang.String getXmlString() {
        return xmlString;
    }
    
    public void setXmlString(java.lang.String xmlString) {
        this.xmlString = xmlString;
    }
    
    public com.amalto.core.webservice.WSDataModelPK getWsDataModelPK() {
        return wsDataModelPK;
    }
    
    public void setWsDataModelPK(com.amalto.core.webservice.WSDataModelPK wsDataModelPK) {
        this.wsDataModelPK = wsDataModelPK;
    }
    
    public com.amalto.core.webservice.WSOperatorType getOperatortype() {
        return operatortype;
    }
    
    public void setOperatortype(com.amalto.core.webservice.WSOperatorType operatortype) {
        this.operatortype = operatortype;
    }
}
