/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.configurationinfo.ejb.local;

import com.amalto.core.server.ConfigurationInfo;

/**
 * Local interface for ConfigurationInfoCtrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ConfigurationInfoCtrlLocal extends javax.ejb.EJBLocalObject, ConfigurationInfo {
}
