/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.groovy.ejb.local;

/**
 * Local home interface for GroovyPluginBean.
 * @xdoclet-generated at 18-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GroovyPluginBeanLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GroovyPluginBeanLocal";
   public static final String JNDI_NAME="amalto/local/transformer/plugin/groovy";

   public com.amalto.core.plugin.base.groovy.ejb.local.GroovyPluginBeanLocal create()
      throws javax.ejb.CreateException;

}
