 /*
 * Generated by XDoclet - Do not edit!
 * this class was prodiuced by xdoclet automagically...
 */
package com.amalto.core.ejb.remote;

import java.util.*;

import com.amalto.xmlserver.interfaces.IWhereItem;

 /**
 * This class is remote adapter to ItemCtrl2. It provides convenient way to access
 * facade session bean. Inverit from this class to provide reasonable caching and event handling capabilities.
 *
 * Remote facade for ItemCtrl2.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */

public class ItemCtrl2Remote extends Observable
{
    static ItemCtrl2Remote _instance = null;
    public static ItemCtrl2Remote getInstance() {
        if(_instance == null) {
	   _instance = new ItemCtrl2Remote();
	}
	return _instance;
    }

  /**
   * cached remote session interface
   */
  com.amalto.core.ejb.remote.ItemCtrl2 _session = null;
  /**
   * return session bean remote interface
   */
   protected com.amalto.core.ejb.remote.ItemCtrl2 getSession() {
      try {
   	if(_session == null) {
	   _session = com.amalto.core.ejb.local.ItemCtrl2Util.getHome().create();
	}
	return _session;
      } catch(Exception ex) {
        // just catch it here and return null.
        // somebody can provide better solution
	ex.printStackTrace();
	return null;
      }
   }

   public com.amalto.core.ejb.ItemPOJOPK putItem ( com.amalto.core.ejb.ItemPOJO item,com.amalto.core.objects.datamodel.ejb.DataModelPOJO datamodel )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.ItemPOJOPK retval;
       retval =  getSession().putItem( item,datamodel );

      return retval;

   }

   public com.amalto.core.ejb.ItemPOJOPK updateItemMetadata ( com.amalto.core.ejb.ItemPOJO item )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.ItemPOJOPK retval;
       retval =  getSession().updateItemMetadata( item );

      return retval;

   }

   public com.amalto.core.ejb.ItemPOJO getItem ( com.amalto.core.ejb.ItemPOJOPK pk )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.ItemPOJO retval;
       retval =  getSession().getItem( pk );

      return retval;

   }

   public com.amalto.core.ejb.ItemPOJO getItem ( java.lang.String revisionID,com.amalto.core.ejb.ItemPOJOPK pk )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.ItemPOJO retval;
       retval =  getSession().getItem( revisionID,pk );

      return retval;

   }

   public boolean isItemModifiedByOther ( com.amalto.core.ejb.ItemPOJOPK item,long time )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        boolean retval;
       retval =  getSession().isItemModifiedByOther( item,time );

      return retval;

   }

   public com.amalto.core.ejb.ItemPOJO existsItem ( com.amalto.core.ejb.ItemPOJOPK pk )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.ItemPOJO retval;
       retval =  getSession().existsItem( pk );

      return retval;

   }

   public com.amalto.core.ejb.ItemPOJOPK deleteItem ( com.amalto.core.ejb.ItemPOJOPK pk,boolean override )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.ItemPOJOPK retval;
       retval =  getSession().deleteItem( pk, override);

      return retval;

   }

   public int deleteItems ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.lang.String conceptName,com.amalto.xmlserver.interfaces.IWhereItem search,int spellThreshold,boolean override )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        int retval;
       retval =  getSession().deleteItems( dataClusterPOJOPK,conceptName,search,spellThreshold,override );

      return retval;

   }

   public com.amalto.core.ejb.DroppedItemPOJOPK dropItem ( com.amalto.core.ejb.ItemPOJOPK itemPOJOPK,java.lang.String partPath,boolean override )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.DroppedItemPOJOPK retval;
       retval =  getSession().dropItem( itemPOJOPK,partPath,override );

      return retval;

   }

   public java.util.ArrayList viewSearch ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,com.amalto.core.objects.view.ejb.ViewPOJOPK viewPOJOPK,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold,int start,int limit )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().viewSearch( dataClusterPOJOPK,viewPOJOPK,whereItem,spellThreshold,start,limit );

      return retval;

   }

   public java.util.ArrayList viewSearch ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,com.amalto.core.objects.view.ejb.ViewPOJOPK viewPOJOPK,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold,java.lang.String orderBy,java.lang.String direction,int start,int limit )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().viewSearch( dataClusterPOJOPK,viewPOJOPK,whereItem,spellThreshold,orderBy,direction,start,limit );

      return retval;

   }

   public java.util.ArrayList xPathsSearch ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.lang.String forceMainPivot,java.util.ArrayList viewablePaths,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold,int start,int limit,boolean returnCount )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().xPathsSearch( dataClusterPOJOPK,forceMainPivot,viewablePaths,whereItem,spellThreshold,start,limit,returnCount );

      return retval;

   }

   public java.util.ArrayList xPathsSearch ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.lang.String forceMainPivot,java.util.ArrayList viewablePaths,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold,java.lang.String orderBy,java.lang.String direction,int start,int limit,boolean returnCount)
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().xPathsSearch( dataClusterPOJOPK,forceMainPivot,viewablePaths,whereItem,spellThreshold,orderBy,direction,start,limit,returnCount );

      return retval;

   }

   public java.util.ArrayList getItemsPivotIndex ( java.lang.String clusterName,java.lang.String mainPivotName,java.util.LinkedHashMap pivotWithKeys,java.lang.String[] indexPaths,com.amalto.xmlserver.interfaces.IWhereItem whereItem,java.lang.String[] pivotDirections,java.lang.String[] indexDirections,int start,int limit )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().getItemsPivotIndex( clusterName,mainPivotName,pivotWithKeys,indexPaths,whereItem,pivotDirections,indexDirections,start,limit );

      return retval;

   }

   public java.util.ArrayList getChildrenItems ( java.lang.String clusterName,java.lang.String conceptName,java.lang.String[] PKXpaths,java.lang.String FKXpath,java.lang.String labelXpath,java.lang.String fatherPK,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int start,int limit )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().getChildrenItems( clusterName,conceptName,PKXpaths,FKXpath,labelXpath,fatherPK,whereItem,start,limit );

      return retval;

   }

   public long count ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.lang.String conceptName,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        long retval;
       retval =  getSession().count( dataClusterPOJOPK,conceptName,whereItem,spellThreshold );

      return retval;

   }

   public java.util.ArrayList quickSearch ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,com.amalto.core.objects.view.ejb.ViewPOJOPK viewPOJOPK,java.lang.String searchValue,boolean matchAllWords,int spellThreshold,java.lang.String orderBy,java.lang.String direction,int start,int limit )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().quickSearch( dataClusterPOJOPK,viewPOJOPK,searchValue,matchAllWords,spellThreshold,orderBy,direction,start,limit );

      return retval;

   }

   public java.util.ArrayList getFullPathValues ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.lang.String businessElementPath,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold,java.lang.String orderBy,java.lang.String direction )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().getFullPathValues( dataClusterPOJOPK,businessElementPath,whereItem,spellThreshold,orderBy,direction );

      return retval;

   }

   public void extractUsingTransformerThroughView ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,com.amalto.core.objects.transformers.v2.util.TransformerContext context,com.amalto.core.objects.transformers.v2.util.TransformerCallBack globalCallBack,com.amalto.core.objects.view.ejb.ViewPOJOPK viewPOJOPK,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold,java.lang.String orderBy,java.lang.String direction,int start,int limit )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
      getSession().extractUsingTransformerThroughView( dataClusterPOJOPK,context,globalCallBack,viewPOJOPK,whereItem,spellThreshold,orderBy,direction,start,limit );

   }

   public com.amalto.core.objects.transformers.v2.util.TransformerContext extractUsingTransformerThroughView ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,com.amalto.core.objects.transformers.v2.ejb.TransformerV2POJOPK transformerPOJOPK,com.amalto.core.objects.view.ejb.ViewPOJOPK viewPOJOPK,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold,java.lang.String orderBy,java.lang.String direction,int start,int limit )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.objects.transformers.v2.util.TransformerContext retval;
       retval =  getSession().extractUsingTransformerThroughView( dataClusterPOJOPK,transformerPOJOPK,viewPOJOPK,whereItem,spellThreshold,orderBy,direction,start,limit );

      return retval;

   }

   public java.util.ArrayList runQuery ( java.lang.String revisionID,com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.lang.String query,java.lang.String[] parameters )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().runQuery( revisionID,dataClusterPOJOPK,query,parameters );

      return retval;

   }

   public java.util.Map getConceptsInDataCluster ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.Map retval;
       retval =  getSession().getConceptsInDataCluster( dataClusterPOJOPK );

      return retval;

   }

   public java.util.Map getConceptsInDataCluster ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,com.amalto.core.objects.universe.ejb.UniversePOJO universe )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.Map retval;
       retval =  getSession().getConceptsInDataCluster( dataClusterPOJOPK,universe );

      return retval;

   }

   public long countItemsByCustomFKFilters ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.lang.String conceptName,java.lang.String injectedXpath )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        long retval;
       retval =  getSession().countItemsByCustomFKFilters( dataClusterPOJOPK,conceptName,injectedXpath );

      return retval;

   }

   public java.util.ArrayList getItemsByCustomFKFilters ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.util.ArrayList viewablePaths,java.lang.String injectedXpath,IWhereItem whereItem,int start,int limit,java.lang.String orderbyPath,java.lang.String direction,boolean returnCount )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().getItemsByCustomFKFilters( dataClusterPOJOPK,viewablePaths,injectedXpath,whereItem,start,limit,orderbyPath,direction,returnCount );

      return retval;

   }

   public java.util.ArrayList getItems ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.lang.String conceptName,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold,int start,int limit,boolean totalCountOnFirstRow )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().getItems( dataClusterPOJOPK,conceptName,whereItem,spellThreshold,start,limit,totalCountOnFirstRow );

      return retval;

   }

   public java.util.ArrayList getItems ( com.amalto.core.objects.datacluster.ejb.DataClusterPOJOPK dataClusterPOJOPK,java.lang.String conceptName,com.amalto.xmlserver.interfaces.IWhereItem whereItem,int spellThreshold,java.lang.String orderBy,java.lang.String direction,int start,int limit,boolean totalCountOnFirstRow )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.ArrayList retval;
       retval =  getSession().getItems( dataClusterPOJOPK,conceptName,whereItem,spellThreshold,orderBy,direction,start,limit,totalCountOnFirstRow );

      return retval;

   }

  /**
   * override this method to provide feedback to interested objects
   * in case collections were changed.
   */
  public void invalidate() {

  	setChanged();
	notifyObservers();
  }
}
