/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.role.ejb.local;

/**
 * Local interface for RoleCtrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface RoleCtrlLocal extends javax.ejb.EJBLocalObject, Role {
}
